import { Scheme } from "./types";

export const SCHEMES_DB: Scheme[] = [ 
  { 
    id: 1, 
    name: "e-Kalyan Scholarship (Post-Matric)", 
    hindiName: "ई-कल्याण छात्रवृत्ति (मैट्रिकोत्तर)",
    type: "State",
    categoryHeading: "📚 Education Support", 
    hindiCategoryHeading: "📚 पढ़ाई के लिए (शिक्षा)",
    desc: "Financial assistance for students from SC, ST, and OBC categories.", 
    hindiDesc: "झारखंड सरकार और केंद्र सरकार की छात्रवृत्ति।",
    minAge: 15, 
    maxAge: 35, 
    gender: "Any", 
    maxIncome: 250000, 
    categories: ["SC", "ST", "OBC"], 
    occupation: ["Student"],
    details: "• **Eligibility:** Residents of Jharkhand with annual family income below ₹2.5 Lakh.\n• **Documents:** Aadhaar, Caste, Income, Residence, Bonafide Certificates.\n• **Website:** ekalyan.cgg.gov.in", 
    hindiDetails: "• **कौन आवेदन कर सकता है:** झारखंड के निवासी, और परिवार की आय ₹2.5 लाख से कम हो।\n• **दस्तावेज:** आधार, जाति, आय, आवासीय, बोनाफाइड।\n• **वेबसाइट:** ekalyan.cgg.gov.in",
    launchYear: "2013", 
    lastVerified: "March 15, 2026",
    lastDate: "January 31, 2026 (for session 2025-26)",
    detailedContent: [
      {
        title: "Simple Explanation",
        icon: "1️⃣",
        content: "e-Kalyan is an initiative by the Government of Jharkhand. Its primary objective is to significantly increase the participation of students from Scheduled Tribes (ST), Scheduled Castes (SC), and Backward Classes (BC) in post-matric education. The scheme aims to provide them with equal opportunities for education, encourage them to pursue higher studies, and ultimately reduce dropout rates among these groups."
      },
      {
        title: "Ways to Apply",
        icon: "2️⃣",
        content: "The e-Kalyan portal primarily facilitates online services.\n\nScholarship Applications: Students typically apply for various post-matric scholarships online through the e-Kalyan portal. Specific application windows and detailed instructions are usually available on the official website.\n\nGrievance Registration: Students can also register grievances related to e-Kalyan services through an online form. This service is fully online."
      },
      {
        title: "Step-by-Step Process",
        icon: "3️⃣",
        content: "For Grievance Registration:\n1. Visit the official Government Services Portal of India or the e-Kalyan portal.\n2. Locate the \"e-Kalyan Grievance Registration Form for Students, Jharkhand.\"\n3. Fill in the required details in the online form.\n4. Submit the form electronically.\n\nFor Scholarship Applications:\n1. Registration: Creating an account on the e-Kalyan portal.\n2. Application Form: Filling out the online application form with personal, academic, and income details.\n3. Document Upload: Uploading scanned copies of required documents.\n4. Submission: Final submission of the application.\n5. Tracking: Checking the application status online."
      },
      {
        title: "Documents Required",
        icon: "4️⃣",
        content: "Common documents typically include:\n• Aadhaar Card\n• Caste Certificate\n• Income Certificate\n• Residence Certificate\n• Previous Year's Mark Sheets\n• Bank Account Details\n• College/School Bonafide Certificate"
      },
      {
        title: "Who is Eligible",
        icon: "6️⃣",
        content: "Students belonging to the following categories are eligible for benefits under e-Kalyan, specifically for post-matric education:\n• Scheduled Tribes (ST)\n• Scheduled Castes (SC)\n• Backward Classes (BC)\n\nThese schemes are primarily for students from Jharkhand."
      },
      {
        title: "Official Apply Links",
        icon: "9️⃣",
        content: "• e-Kalyan Grievance Registration Form ↗\n• e-Kalyan Official Portal FAQs ↗\n• e-Kalyan Application Status ↗"
      }
    ],
    applyLinks: [
      { label: "e-Kalyan Grievance Form", url: "https://ekalyan.cgg.gov.in" },
      { label: "Check Application Status", url: "https://ekalyan.cgg.gov.in" }
    ],
    sources: ["e-Kalyan Official Portal", "Jharkhand Welfare Dept"]
  }, 
  { 
    id: 2, 
    name: "Mukhyamantri Maiyan Samman Yojana", 
    hindiName: "मुख्यमंत्री मंईयां सम्मान योजना",
    type: "State",
    categoryHeading: "👩 Women Empowerment", 
    hindiCategoryHeading: "👩 महिला सशक्तिकरण",
    desc: "Monthly financial assistance for the empowerment of women in Jharkhand.", 
    hindiDesc: "झारखंड की महिलाओं के लिए मासिक आर्थिक सहायता।",
    minAge: 18, 
    maxAge: 50, 
    gender: "Female", 
    maxIncome: 800000, 
    categories: ["General", "SC", "ST", "OBC"], 
    geography: "Rural",
    target_ration_card: ["Pink", "Yellow", "Green"],
    details: "• **Benefit:** ₹2500 per month directly into bank account.\n• **Documents:** Aadhaar, Bank Passbook, Ration Card.\n• **Portal:** mmmsy.jharkhand.gov.in or nearest Pragya Kendra.", 
    hindiDetails: "• **लाभ:** ₹2500 प्रति माह सीधे बैंक खाते में।\n• **दस्तावेज:** आधार, बैंक पासबुक, राशन कार्ड।\n• **कहाँ:** mmmsy.jharkhand.gov.in या प्रज्ञा केंद्र।",
    launchYear: "August 1, 2024", 
    lastVerified: "March 15, 2026",
    detailedContent: [
      {
        title: "Simple Explanation",
        icon: "1️⃣",
        content: "The Jharkhand Mukhyamantri Maiyan Samman Yojana (JMMSY) is a flagship welfare scheme aimed at providing financial independence to women. It provides a monthly 'honorarium' to eligible women to support their daily needs and improve their social standing."
      },
      {
        title: "Ways to Apply",
        icon: "2️⃣",
        content: "Online: Through the official portal mmmsy.jharkhand.gov.in via CSC/Pragya Kendras.\n\nOffline: By submitting physical forms at specialized camps (Panchayat level) or Anganwadi centers."
      },
      {
        title: "Step-by-Step Process",
        icon: "3️⃣",
        content: "1. Registration: Visit the nearest Pragya Kendra or Panchayat Camp.\n2. Documentation: Provide Aadhaar and Bank details.\n3. Verification: Field verification by local authorities.\n4. Approval: Once approved, the first installment is credited via DBT.\n5. Status: Check status on mmmsy.jharkhand.gov.in using Aadhaar number."
      },
      {
        title: "Documents Required",
        icon: "4️⃣",
        content: "• Aadhaar Card (Linked to mobile & bank)\n• Bank Passbook (Aadhaar Seeded)\n• Ration Card (Green/Yellow/Pink)\n• Passport size photograph\n• Self-Declaration Form"
      },
      {
        title: "Who is Eligible",
        icon: "6️⃣",
        content: "• Female resident of Jharkhand.\n• Age: 18 to 50 years.\n• Family must hold a valid Ration Card.\n• Not a regular government employee or taxpayer."
      },
      {
        title: "Official Apply Links",
        icon: "9️⃣",
        content: "• JMMSY Official Portal ↗\n• Check Application Status ↗"
      }
    ],
    applyLinks: [
      { label: "JMMSY Official Portal", url: "https://mmmsy.jharkhand.gov.in" },
      { label: "Check Status", url: "https://mmmsy.jharkhand.gov.in" }
    ],
    sources: ["WCD Department, Jharkhand", "Official MMMSY Portal"]
  }, 
  { 
    id: 3, 
    name: "Guruji Student Credit Card", 
    hindiName: "गुरुजी स्टूडेंट क्रेडिट कार्ड योजना",
    type: "State",
    categoryHeading: "🎓 Higher Education Loan", 
    hindiCategoryHeading: "🎓 उच्च शिक्षा ऋण",
    desc: "Low-interest education loans for students without any collateral.", 
    hindiDesc: "बिना किसी सुरक्षा (collateral) के पढ़ाई के लिए सस्ता ऋण।",
    minAge: 18, 
    maxAge: 40, 
    gender: "Any", 
    maxIncome: 9999999, 
    categories: ["General", "SC", "ST", "OBC"], 
    details: "• **Benefit:** Education loan up to ₹15 Lakh at only 4% simple interest.\n• **Documents:** Aadhaar, PAN Card, Admission Letter.\n• **Portal:** gscc.jharkhand.gov.in", 
    hindiDetails: "• **लाभ:** ₹15 लाख तक का ऋण केवल 4% ब्याज पर।\n• **दस्तावेज:** आधार, पैन, प्रवेश पत्र (Admission letter)।",
    launchYear: "January 21, 2025", 
    lastVerified: "March 15, 2026",
    detailedContent: [
      {
        title: "Simple Explanation",
        icon: "1️⃣",
        content: "The Guruji Student Credit Card (GSCC) scheme provides collateral-free education loans to students of Jharkhand. It aims to ensure that no student is deprived of higher education due to financial constraints."
      },
      {
        title: "Ways to Apply",
        icon: "2️⃣",
        content: "Students can apply online through the official GSCC portal or visit designated help desks in educational institutions."
      },
      {
        title: "Step-by-Step Process",
        icon: "3️⃣",
        content: "1. Online Registration on the GSCC portal.\n2. Filling out the application with academic and institution details.\n3. Uploading required documents (Admission letter, Fee structure).\n4. Bank verification and approval.\n5. Issuance of the Credit Card/Loan disbursement."
      },
      {
        title: "Documents Required",
        icon: "4️⃣",
        content: "• Aadhaar Card of Student & Co-borrower (Parent).\n• PAN Card.\n• 10th/12th Marksheets.\n• Admission Letter from a recognized institution.\n• Detailed Fee Structure.\n• Residence Certificate of Jharkhand."
      },
      {
        title: "Who is Eligible",
        icon: "6️⃣",
        content: "• Resident of Jharkhand.\n• Age up to 40 years.\n• Must have secured admission in a recognized higher education institution (General/Technical/Professional)."
      },
      {
        title: "Official Apply Links",
        icon: "9️⃣",
        content: "• Guruji Student Credit Card Portal ↗"
      }
    ],
    applyLinks: [
      { label: "GSCC Portal", url: "https://gscc.jharkhand.gov.in" }
    ],
    sources: ["Higher Education Dept, Jharkhand"]
  },
  {
    id: 4,
    name: "Abua Awas Yojana",
    hindiName: "अबूआ आवास योजना",
    type: "State",
    categoryHeading: "🏠 Housing Support",
    hindiCategoryHeading: "🏠 आवास सहायता (घर)",
    desc: "A state-funded housing scheme providing 3-room permanent houses to homeless families.",
    hindiDesc: "बेघर परिवारों को 3 कमरों वाला पक्का घर देने की योजना।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 300000,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    details: "• **Benefit:** ₹2 Lakh in 4 installments + 95 days MGNREGA wages.\n• **Documents:** Aadhaar, Ration Card, Job Card, Bank Passbook.\n• **Portal:** Nearest Block Office or Panchayat Camp.",
    hindiDetails: "• **लाभ:** ₹2 लाख (4 किस्तों में) + 95 दिनों की मनरेगा मजदूरी।\n• **दस्तावेज:** आधार, राशन कार्ड, जॉब कार्ड, बैंक पासबुक।",
    launchYear: "2023",
    lastVerified: "March 15, 2026",
    detailedContent: [
      {
        title: "Simple Explanation",
        icon: "1️⃣",
        content: "The Abua Awas Yojana is Jharkhand's own housing scheme for those who were left out of PMAY (Pradhan Mantri Awas Yojana). It provides a decent 3-room house with a kitchen."
      },
      {
        title: "Step-by-Step Process",
        icon: "3️⃣",
        content: "1. Apply during 'Aapki Yojana, Aapki Sarkar, Aapke Dwar' camps.\n2. Verification by Gram Sabha and Block officials.\n3. Geo-tagging of the old kucha house.\n4. Approval and release of the first installment."
      },
      {
        title: "Documents Required",
        icon: "4️⃣",
        content: "• Aadhaar Card\n• MGNREGA Job Card\n• Ration Card\n• Bank Passbook\n• Photograph of current house"
      }
    ],
    sources: ["Rural Development Dept, Jharkhand"]
  },
  {
    id: 5,
    name: "Savitribai Phule Kishori Samriddhi Yojana",
    hindiName: "सावित्रीबाई फुले किशोरी समृद्धि योजना",
    type: "State",
    categoryHeading: "👧 Girl Child Welfare",
    hindiCategoryHeading: "👧 बालिका कल्याण",
    desc: "Financial assistance to adolescent girls for education and to prevent child marriage.",
    hindiDesc: "किशोरियों की शिक्षा और बाल विवाह रोकने के लिए आर्थिक सहायता।",
    minAge: 13,
    maxAge: 19,
    gender: "Female",
    maxIncome: 500000,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Student"],
    details: "• **Benefit:** Up to ₹40,000 total assistance in grades 8 to 12 and at age 18.\n• **Documents:** School Certificate, Aadhaar, Mother's Aadhaar.\n• **Portal:** Apply via School or Anganwadi.",
    hindiDetails: "• **लाभ:** कक्षा 8 से 12 तक और 18 साल की उम्र पर कुल ₹40,000 तक की सहायता।\n• **दस्तावेज:** स्कूल सर्टिफिकेट, आधार, माता का आधार।",
    launchYear: "2022",
    lastVerified: "March 15, 2026",
    detailedContent: [
      {
        title: "Benefits Breakdown",
        icon: "💰",
        content: "Class 8 & 9: ₹2,500 each | Class 10, 11 & 12: ₹5,000 each | Age 18-19: ₹20,000 one-time grant."
      }
    ],
    sources: ["WCD Department, Jharkhand"]
  },
  {
    id: 6,
    name: "Mukhyamantri Gram Gaadi Yojana",
    hindiName: "मुख्यमंत्री ग्राम गाड़ी योजना",
    type: "State",
    categoryHeading: "🚌 Rural Transport",
    hindiCategoryHeading: "🚌 ग्रामीण परिवहन",
    desc: "Free or subsidized travel for students, seniors, and disabled citizens in rural areas.",
    hindiDesc: "ग्रामीण क्षेत्रों में छात्रों, बुजुर्गों और दिव्यांगों के लिए मुफ्त या रियायती यात्रा।",
    minAge: 5,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    details: "• **Benefit:** Free travel cards for eligible categories.\n• **Documents:** ID Card, Category Certificate.\n• **Portal:** District Transport Office.",
    hindiDetails: "• **लाभ:** पात्र श्रेणियों के लिए मुफ्त यात्रा पास।\n• **दस्तावेज:** पहचान पत्र, श्रेणी प्रमाण पत्र।",
    launchYear: "2024",
    lastVerified: "March 15, 2026",
    sources: ["Transport Dept, Jharkhand"]
  },
  {
    id: 7,
    name: "Birsa Harit Gram Yojana",
    hindiName: "बिरसा हरित ग्राम योजना",
    type: "State",
    categoryHeading: "🌳 Horticulture & Livelihood",
    hindiCategoryHeading: "🌳 बागवानी और आजीविका",
    desc: "Subsidy for fruit plantation on private land to provide sustainable income to rural families.",
    hindiDesc: "ग्रामीण परिवारों को स्थायी आय देने के लिए निजी भूमि पर फलदार वृक्षारोपण।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 200000,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    requires_land: true,
    details: "• **Benefit:** Saplings, fencing, and maintenance labor via MGNREGA.\n• **Documents:** Land Documents, MGNREGA Job Card.\n• **Portal:** BDO Office / Gram Panchayat.",
    hindiDetails: "• **लाभ:** फलदार पौधे, घेराबंदी और मनरेगा के तहत रखरखाव।\n• **दस्तावेज:** जमीन के कागज, जॉब कार्ड।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["Rural Development Dept, Jharkhand"]
  },
  {
    id: 8,
    name: "Mukhyamantri Pashudhan Vikas Yojana",
    hindiName: "मुख्यमंत्री पशुधन विकास योजना",
    type: "State",
    categoryHeading: "🐄 Animal Husbandry",
    hindiCategoryHeading: "🐄 पशुपालन विकास",
    desc: "Subsidy on dairy, poultry, and goat farming to boost rural economy.",
    hindiDesc: "ग्रामीण अर्थव्यवस्था को बढ़ावा देने के लिए डेयरी, मुर्गी पालन और बकरी पालन पर सब्सिडी।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 500000,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** 50% to 90% subsidy on purchase of livestock.\n• **Documents:** Aadhaar, Bank Passbook, Training Certificate (optional).\n• **Portal:** District Animal Husbandry Office.",
    hindiDetails: "• **लाभ:** पशुओं की खरीद पर 50% से 90% तक की सब्सिडी।\n• **दस्तावेज:** आधार, बैंक पासबुक, प्रशिक्षण प्रमाण पत्र।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Animal Husbandry Dept, Jharkhand"]
  },
  {
    id: 9,
    name: "Jharkhand State Food Security Scheme (Green Ration Card)",
    hindiName: "झारखंड राज्य खाद्य सुरक्षा योजना (हरा राशन कार्ड)",
    type: "State",
    categoryHeading: "🍎 Food Security",
    hindiCategoryHeading: "🍎 खाद्य सुरक्षा (राशन)",
    desc: "Subsidized food grains for families not covered under the National Food Security Act.",
    hindiDesc: "उन परिवारों के लिए रियायती अनाज जो राष्ट्रीय खाद्य सुरक्षा अधिनियम के तहत नहीं आते।",
    minAge: 1,
    maxAge: 99,
    gender: "Any",
    maxIncome: 100000,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** 5kg food grains per person at ₹1/kg.\n• **Documents:** Aadhaar, Self-declaration of income.\n• **Portal:** aahar.jharkhand.gov.in",
    hindiDetails: "• **लाभ:** ₹1/किलो की दर से प्रति व्यक्ति 5 किलो अनाज।\n• **दस्तावेज:** आधार, आय का स्व-घोषणा पत्र।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["Food & Public Distribution Dept, Jharkhand"]
  },
  {
    id: 10,
    name: "Marang Gomke Jaipal Singh Munda Transnational Scholarship",
    hindiName: "मरांग गोमके जयपाल सिंह मुंडा विदेशी छात्रवृत्ति",
    type: "State",
    categoryHeading: "🌍 Overseas Education",
    hindiCategoryHeading: "🌍 विदेश में उच्च शिक्षा",
    desc: "Full funding for higher studies (Masters/M.Phil) in UK and Ireland for talented students.",
    hindiDesc: "प्रतिभावान छात्रों के लिए यूके और आयरलैंड में उच्च शिक्षा (मास्टर्स) के लिए पूर्ण वित्त पोषण।",
    minAge: 18,
    maxAge: 35,
    gender: "Any",
    maxIncome: 1200000,
    categories: ["SC", "ST", "OBC", "Minority"],
    occupation: ["Student"],
    details: "• **Benefit:** Tuition fees, living expenses, and airfare covered.\n• **Documents:** Admission offer, Caste Certificate, Income Certificate.\n• **Portal:** mgjsmscholarship.jharkhand.gov.in",
    hindiDetails: "• **लाभ:** ट्यूशन फीस, रहने का खर्च और हवाई किराया।\n• **दस्तावेज:** प्रवेश प्रस्ताव पत्र, जाति प्रमाण पत्र, आय प्रमाण पत्र।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Welfare Dept, Jharkhand"]
  },
  {
    id: 11,
    name: "Mukhyamantri Sarvajan Pension Yojana",
    hindiName: "मुख्यमंत्री सर्वजन पेंशन योजना",
    type: "State",
    categoryHeading: "👴 Social Security",
    hindiCategoryHeading: "👴 सामाजिक सुरक्षा (पेंशन)",
    desc: "Universal pension scheme for seniors, widows, and disabled persons without complex criteria.",
    hindiDesc: "बुजुर्गों, विधवाओं और दिव्यांगों के लिए बिना किसी जटिल मानदंड के सार्वभौमिक पेंशन योजना।",
    minAge: 60,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    isPension: true,
    details: "• **Benefit:** ₹1,000 per month directly to bank account.\n• **Documents:** Aadhaar, Voter ID, Bank Details.\n• **Portal:** Block Office / Pragya Kendra.",
    hindiDetails: "• **लाभ:** ₹1,000 प्रति माह सीधे बैंक खाते में।\n• **दस्तावेज:** आधार, वोटर आईडी, बैंक विवरण।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["WCD Department, Jharkhand"]
  },
  {
    id: 12,
    name: "Jharkhand Mukhyamantri Sarthi Yojana",
    hindiName: "झारखंड मुख्यमंत्री सारथी योजना",
    type: "State",
    categoryHeading: "🛠️ Skill Development",
    hindiCategoryHeading: "🛠️ कौशल विकास (ट्रेनिंग)",
    desc: "Free skill training and placement assistance for unemployed youth.",
    hindiDesc: "बेरोजगार युवाओं के लिए मुफ्त कौशल प्रशिक्षण और प्लेसमेंट सहायता।",
    minAge: 18,
    maxAge: 35,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Unemployed"],
    details: "• **Benefit:** Free training + ₹1,000-1,500 monthly allowance during training.\n• **Documents:** Aadhaar, Educational Certificates.\n• **Portal:** Jharkhand Skill Development Mission.",
    hindiDetails: "• **लाभ:** मुफ्त ट्रेनिंग + ट्रेनिंग के दौरान ₹1,000-1,500 मासिक भत्ता।\n• **दस्तावेज:** आधार, शैक्षणिक प्रमाण पत्र।",
    launchYear: "2023",
    lastVerified: "March 15, 2026",
    sources: ["Labour & Employment Dept, Jharkhand"]
  },
  {
    id: 13,
    name: "Mukhyamantri Rojgar Srijan Yojana",
    hindiName: "मुख्यमंत्री रोजगार सृजन योजना",
    type: "State",
    categoryHeading: "💼 Entrepreneurship Loan",
    hindiCategoryHeading: "💼 स्वरोजगार ऋण (बिजनेस)",
    desc: "Subsidized loans for youth to start their own business or purchase commercial vehicles.",
    hindiDesc: "युवाओं को अपना व्यवसाय शुरू करने या वाणिज्यिक वाहन खरीदने के लिए रियायती ऋण।",
    minAge: 18,
    maxAge: 45,
    gender: "Any",
    maxIncome: 500000,
    categories: ["SC", "ST", "OBC", "Minority", "Disabled"],
    details: "• **Benefit:** Loan up to ₹25 Lakh with 40% subsidy (max ₹5 Lakh).\n• **Documents:** Project Report, Caste Certificate, Aadhaar.\n• **Portal:** Jharkhand Tribal Development Society / District Offices.",
    hindiDetails: "• **लाभ:** 40% सब्सिडी के साथ ₹25 लाख तक का ऋण।\n• **दस्तावेज:** प्रोजेक्ट रिपोर्ट, जाति प्रमाण पत्र, आधार।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Welfare Dept, Jharkhand"]
  },
  {
    id: 14,
    name: "Paddy Procurement Scheme (MSP)",
    hindiName: "धान अधिप्राप्ति योजना (एमएसपी)",
    type: "State",
    categoryHeading: "🌾 Agriculture Support",
    hindiCategoryHeading: "🌾 कृषि सहायता (धान)",
    desc: "Direct purchase of paddy from farmers at Minimum Support Price plus state bonus.",
    hindiDesc: "न्यूनतम समर्थन मूल्य (MSP) और राज्य बोनस पर किसानों से धान की सीधी खरीद।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** Guaranteed price + Bonus paid directly via DBT.\n• **Documents:** Farmer Registration ID, Land Receipt.\n• **Portal:** Jharkhand Kharif Procurement Portal.",
    hindiDetails: "• **लाभ:** गारंटीकृत मूल्य + सीधा बैंक खाते में भुगतान।\n• **दस्तावेज:** किसान पंजीकरण आईडी, लगान रसीद।",
    launchYear: "Every Kharif Season",
    lastVerified: "March 15, 2026",
    sources: ["Food & Civil Supplies Dept, Jharkhand"]
  },
  {
    id: 15,
    name: "Mukhyamantri Kanyadan Yojana",
    hindiName: "मुख्यमंत्री कन्यादान योजना",
    type: "State",
    categoryHeading: "💍 Marriage Assistance",
    hindiCategoryHeading: "💍 विवाह सहायता",
    desc: "One-time financial assistance to BPL families for the marriage of their daughters.",
    hindiDesc: "बीपीएल परिवारों को उनकी बेटियों की शादी के लिए एकमुश्त वित्तीय सहायता।",
    minAge: 18,
    maxAge: 99,
    gender: "Female",
    maxIncome: 72000,
    categories: ["General", "SC", "ST", "OBC"],
    target_ration_card: ["Yellow", "Pink"],
    details: "• **Benefit:** ₹30,000 financial assistance.\n• **Documents:** BPL Card, Age Proof of Bride, Marriage Card.\n• **Portal:** Block Development Office.",
    hindiDetails: "• **लाभ:** ₹30,000 की वित्तीय सहायता।\n• **दस्तावेज:** बीपीएल कार्ड, दुल्हन का आयु प्रमाण, शादी का कार्ड।",
    launchYear: "2004",
    lastVerified: "March 15, 2026",
    sources: ["WCD Department, Jharkhand"]
  },
  {
    id: 16,
    name: "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
    hindiName: "प्रधानमंत्री मातृ वंदना योजना",
    type: "Central",
    categoryHeading: "🤰 Maternity Benefit",
    hindiCategoryHeading: "🤰 मातृत्व लाभ",
    desc: "Cash incentive for pregnant and lactating mothers for the first living child.",
    hindiDesc: "गर्भवती और स्तनपान कराने वाली माताओं के लिए नकद प्रोत्साहन राशि।",
    minAge: 19,
    maxAge: 45,
    gender: "Female",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** ₹5,000 in three installments.\n• **Documents:** MCP Card, Aadhaar, Bank Passbook.\n• **Portal:** pmmvy-cas.nic.in or Anganwadi.",
    hindiDetails: "• **लाभ:** तीन किस्तों में ₹5,000।\n• **दस्तावेज:** एमसीपी कार्ड, आधार, बैंक पासबुक।",
    launchYear: "2017",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of WCD, GoI"]
  },
  {
    id: 17,
    name: "Ayushman Bharat - PMJAY",
    hindiName: "आयुष्मान भारत - पीएमजेएवाई",
    type: "Central",
    categoryHeading: "🏥 Health Insurance",
    hindiCategoryHeading: "🏥 स्वास्थ्य बीमा",
    desc: "World's largest health insurance scheme providing ₹5 Lakh cover per family per year.",
    hindiDesc: "दुनिया की सबसे बड़ी स्वास्थ्य बीमा योजना, प्रति परिवार ₹5 लाख का कवर।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    target_ration_card: ["Yellow", "Pink", "Green"],
    details: "• **Benefit:** Cashless treatment up to ₹5 Lakh in empanelled hospitals.\n• **Documents:** Ration Card, Aadhaar Card.\n• **Portal:** pmjay.gov.in or nearest Common Service Centre.",
    hindiDetails: "• **लाभ:** सूचीबद्ध अस्पतालों में ₹5 लाख तक का कैशलेस इलाज।\n• **दस्तावेज:** राशन कार्ड, आधार कार्ड।",
    launchYear: "2018",
    lastVerified: "March 15, 2026",
    sources: ["National Health Authority, GoI"]
  },
  {
    id: 18,
    name: "PM-Kisan Samman Nidhi",
    hindiName: "पीएम-किसान सम्मान निधि",
    type: "Central",
    categoryHeading: "👨‍🌾 Income Support for Farmers",
    hindiCategoryHeading: "👨‍🌾 किसानों के लिए आय सहायता",
    desc: "Annual financial support of ₹6,000 to all land-holding farmer families in India.",
    hindiDesc: "भारत के सभी भूमिधारक किसान परिवारों को ₹6,000 की वार्षिक वित्तीय सहायता।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** ₹6,000 per year in three equal installments of ₹2,000.\n• **Documents:** Land Records, Aadhaar, Bank Account.\n• **Portal:** pmkisan.gov.in",
    hindiDetails: "• **लाभ:** ₹2,000 की तीन समान किस्तों में ₹6,000 प्रति वर्ष।\n• **दस्तावेज:** भूमि रिकॉर्ड, आधार, बैंक खाता।",
    launchYear: "2019",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Agriculture, GoI"]
  },
  {
    id: 19,
    name: "Mukhyamantri Shramik Yojana",
    hindiName: "मुख्यमंत्री श्रमिक योजना",
    type: "State",
    categoryHeading: "👷 Urban Employment",
    hindiCategoryHeading: "👷 शहरी रोजगार",
    desc: "100 days of guaranteed wage employment in a financial year for urban unskilled workers.",
    hindiDesc: "शहरी अकुशल श्रमिकों के लिए एक वित्तीय वर्ष में 100 दिनों के गारंटीकृत मजदूरी रोजगार।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Urban",
    occupation: ["Worker", "Labourer", "Unemployed"],
    details: "• **Benefit:** 100 days work guarantee or unemployment allowance.\n• **Documents:** Aadhaar Card, Urban Address Proof.\n• **Portal:** msy.jharkhand.gov.in",
    hindiDetails: "• **लाभ:** 100 दिन काम की गारंटी या बेरोजगारी भत्ता।\n• **दस्तावेज:** आधार कार्ड, शहरी निवास प्रमाण।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["UDD Department, Jharkhand"]
  },
  {
    id: 20,
    name: "Jharkhand Udiyan Protsahan Yojana",
    hindiName: "झारखंड उद्यान प्रोत्साहन योजना",
    type: "State",
    categoryHeading: "🍎 Horticulture",
    hindiCategoryHeading: "🍎 उद्यानिकी (बागवानी)",
    desc: "Subsidy for protected cultivation like polyhouses and shade nets to grow high-value crops.",
    hindiDesc: "उच्च मूल्य वाली फसलों को उगाने के लिए पॉलीहाउस और शेड नेट जैसी संरक्षित खेती के लिए सब्सिडी।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** Up to 50% subsidy on polyhouse construction.\n• **Documents:** Land possession certificate, Aadhaar.\n• **Portal:** District Horticulture Office.",
    hindiDetails: "• **लाभ:** पॉलीहाउस निर्माण पर 50% तक की सब्सिडी।\n• **दस्तावेज:** भूमि कब्जा प्रमाण पत्र, आधार।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Agriculture Dept, Jharkhand"]
  },
  {
    id: 21,
    name: "PM Vishwakarma Yojana",
    hindiName: "पीएम विश्वकर्मा योजना",
    type: "Central",
    categoryHeading: "🔨 Artisan Support",
    hindiCategoryHeading: "🔨 शिल्पकार सहायता",
    desc: "Support for traditional artisans and craftspeople with training, toolkits, and low-interest loans.",
    hindiDesc: "पारंपरिक कारीगरों और शिल्पकारों को प्रशिक्षण, टूलकिट और कम ब्याज वाले ऋण के साथ सहायता।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Artisan", "Carpenter", "Blacksmith", "Tailor", "Barber"],
    details: "• **Benefit:** ₹15,000 toolkit e-voucher + ₹1-3 Lakh loan at 5% interest.\n• **Documents:** Aadhaar, Bank Details, Skill Certificate.\n• **Portal:** pmvishwakarma.gov.in",
    hindiDetails: "• **लाभ:** ₹15,000 टूलकिट वाउचर + 5% ब्याज पर ₹1-3 लाख का ऋण।\n• **दस्तावेज:** आधार, बैंक विवरण, कौशल प्रमाण पत्र।",
    launchYear: "2023",
    lastVerified: "March 15, 2026",
    sources: ["MSME Ministry, GoI"]
  },
  {
    id: 22,
    name: "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
    hindiName: "प्रधानमंत्री जन धन योजना",
    type: "Central",
    categoryHeading: "🏦 Financial Inclusion",
    hindiCategoryHeading: "🏦 वित्तीय समावेशन (बैंक खाता)",
    desc: "Zero-balance bank accounts with insurance and overdraft facilities for every household.",
    hindiDesc: "प्रत्येक परिवार के लिए बीमा और ओवरड्राफ्ट सुविधाओं के साथ जीरो-बैलेंस बैंक खाते।",
    minAge: 10,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** ₹2 Lakh accident insurance + ₹10,000 overdraft facility.\n• **Documents:** Aadhaar Card.\n• **Portal:** Any bank branch.",
    hindiDetails: "• **लाभ:** ₹2 लाख दुर्घटना बीमा + ₹10,000 ओवरड्राफ्ट सुविधा।\n• **दस्तावेज:** आधार कार्ड।",
    launchYear: "2014",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Finance, GoI"]
  },
  {
    id: 23,
    name: "Sukanya Samriddhi Yojana (SSY)",
    hindiName: "सुकन्या समृद्धि योजना",
    type: "Central",
    categoryHeading: "👧 Girl Child Savings",
    hindiCategoryHeading: "👧 बेटी बचाओ - बचत योजना",
    desc: "A small deposit scheme for the girl child with high-interest rates and tax benefits.",
    hindiDesc: "उच्च ब्याज दरों और कर लाभ के साथ बालिकाओं के लिए एक लघु बचत योजना।",
    minAge: 0,
    maxAge: 10,
    gender: "Female",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** High interest (currently ~8.2%) + Tax exemption under 80C.\n• **Documents:** Birth Certificate of girl, Parent's ID.\n• **Portal:** Post Office or Banks.",
    hindiDetails: "• **लाभ:** उच्च ब्याज दर + 80C के तहत कर छूट।\n• **दस्तावेज:** बेटी का जन्म प्रमाण पत्र, माता-पिता की आईडी।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Finance, GoI"]
  },
  {
    id: 24,
    name: "PM SVANidhi",
    hindiName: "पीएम स्वनिधि",
    type: "Central",
    categoryHeading: "🧺 Street Vendor Support",
    hindiCategoryHeading: "🧺 रेहड़ी-पटरी वालों के लिए ऋण",
    desc: "Micro-credit facility for street vendors to resume their livelihoods in urban areas.",
    hindiDesc: "शहरी क्षेत्रों में रेहड़ी-पटरी वालों को अपनी आजीविका फिर से शुरू करने के लिए सूक्ष्म ऋण सुविधा।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Urban",
    occupation: ["Street Vendor", "Hawker"],
    details: "• **Benefit:** Collateral-free working capital loan up to ₹50,000.\n• **Documents:** Aadhaar, Vending ID Card / LOR.\n• **Portal:** pmsvanidhi.mohua.gov.in",
    hindiDetails: "• **लाभ:** ₹50,000 तक का बिना गारंटी वाला वर्किंग कैपिटल लोन।\n• **दस्तावेज:** आधार, वेंडिंग आईडी कार्ड।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["MoHUA, GoI"]
  },
  {
    id: 25,
    name: "Atal Pension Yojana (APY)",
    hindiName: "अटल पेंशन योजना",
    type: "Central",
    categoryHeading: "👴 Pension for Unorganized Sector",
    hindiCategoryHeading: "👴 असंगठित क्षेत्र के लिए पेंशन",
    desc: "Guaranteed monthly pension for citizens working in the unorganized sector after age 60.",
    hindiDesc: "60 वर्ष की आयु के बाद असंगठित क्षेत्र में काम करने वाले नागरिकों के लिए गारंटीकृत मासिक पेंशन।",
    minAge: 18,
    maxAge: 40,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Monthly pension from ₹1,000 to ₹5,000.\n• **Documents:** Bank Account, Aadhaar.\n• **Portal:** Any bank or post office.",
    hindiDetails: "• **लाभ:** ₹1,000 से ₹5,000 तक मासिक पेंशन।\n• **दस्तावेज:** बैंक खाता, आधार।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["PFRDA, GoI"]
  },
  {
    id: 26,
    name: "PM Shram Yogi Maan-dhan (PM-SYM)",
    hindiName: "प्रधानमंत्री श्रम योगी मान-धन",
    type: "Central",
    categoryHeading: "👷 Worker Social Security",
    hindiCategoryHeading: "👷 श्रमिक सामाजिक सुरक्षा",
    desc: "Voluntary and contributory pension scheme for unorganized workers like rickshaw pullers and maids.",
    hindiDesc: "रिक्शा चालकों और घरेलू सहायिकाओं जैसे असंगठित श्रमिकों के लिए स्वैच्छिक पेंशन योजना।",
    minAge: 18,
    maxAge: 40,
    gender: "Any",
    maxIncome: 180000,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Labourer", "Worker", "Maid", "Driver"],
    details: "• **Benefit:** Minimum assured pension of ₹3,000 per month.\n• **Documents:** Aadhaar, Bank Passbook.\n• **Portal:** maandhan.in or CSC.",
    hindiDetails: "• **लाभ:** प्रति माह ₹3,000 की न्यूनतम सुनिश्चित पेंशन।\n• **दस्तावेज:** आधार, बैंक पासबुक।",
    launchYear: "2019",
    lastVerified: "March 15, 2026",
    sources: ["Labour Ministry, GoI"]
  },
  {
    id: 27,
    name: "Ujjwala Yojana 2.0",
    hindiName: "उज्ज्वला योजना 2.0",
    type: "Central",
    categoryHeading: "🔥 Free LPG Connection",
    hindiCategoryHeading: "🔥 मुफ्त गैस कनेक्शन",
    desc: "Providing clean cooking fuel (LPG) to women from low-income households.",
    hindiDesc: "कम आय वाले परिवारों की महिलाओं को स्वच्छ खाना पकाने का ईंधन (LPG) प्रदान करना।",
    minAge: 18,
    maxAge: 99,
    gender: "Female",
    maxIncome: 200000,
    categories: ["General", "SC", "ST", "OBC"],
    target_ration_card: ["Yellow", "Pink", "Green"],
    details: "• **Benefit:** First LPG cylinder and stove free of cost.\n• **Documents:** Aadhaar, Ration Card, Bank Account.\n• **Portal:** pmuy.gov.in or nearest gas agency.",
    hindiDetails: "• **लाभ:** पहला एलपीजी सिलेंडर और चूल्हा बिल्कुल मुफ्त।\n• **दस्तावेज:** आधार, राशन कार्ड, बैंक खाता।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Petroleum, GoI"]
  },
  {
    id: 28,
    name: "Stand Up India Scheme",
    hindiName: "स्टैंड अप इंडिया योजना",
    type: "Central",
    categoryHeading: "🚀 SC/ST & Women Entrepreneurship",
    hindiCategoryHeading: "🚀 उद्यमिता सहायता (SC/ST/महिला)",
    desc: "Facilitating bank loans between ₹10 Lakh and ₹1 Crore to SC, ST or women borrowers for greenfield enterprises.",
    hindiDesc: "एससी, एसटी या महिला उधारकर्ताओं को नए उद्यमों के लिए ₹10 लाख से ₹1 करोड़ के बीच बैंक ऋण।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["SC", "ST"],
    details: "• **Benefit:** Large loans for manufacturing, services, or trading sector.\n• **Documents:** Project Report, ID Proof, Caste Certificate.\n• **Portal:** standupmitra.in",
    hindiDetails: "• **लाभ:** विनिर्माण, सेवा या व्यापार क्षेत्र के लिए बड़े ऋण।\n• **दस्तावेज:** प्रोजेक्ट रिपोर्ट, आईडी प्रूफ, जाति प्रमाण पत्र।",
    launchYear: "2016",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Finance, GoI"]
  },
  {
    id: 29,
    name: "E-Shram Card",
    hindiName: "ई-श्रम कार्ड",
    type: "Central",
    categoryHeading: "🆔 Unorganized Workers Database",
    hindiCategoryHeading: "🆔 ई-श्रम पोर्टल",
    desc: "Registration of unorganized workers to facilitate social security benefits.",
    hindiDesc: "सामाजिक सुरक्षा लाभों की सुविधा के लिए असंगठित श्रमिकों का पंजीकरण।",
    minAge: 16,
    maxAge: 59,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Worker", "Labourer", "Farmer", "Driver"],
    details: "• **Benefit:** Accidental insurance cover + Ease of receiving DBT benefits.\n• **Documents:** Aadhaar Card, Bank Account.\n• **Portal:** eshram.gov.in",
    hindiDetails: "• **लाभ:** दुर्घटना बीमा कवर + डीबीटी लाभ प्राप्त करने में आसानी।\n• **दस्तावेज:** आधार कार्ड, बैंक खाता।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Labour Ministry, GoI"]
  },
  {
    id: 30,
    name: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    hindiName: "प्रधानमंत्री फसल बीमा योजना",
    type: "Central",
    categoryHeading: "🌾 Crop Insurance",
    hindiCategoryHeading: "🌾 फसल बीमा",
    desc: "Insurance coverage and financial support to farmers in case of failure of any of the notified crops.",
    hindiDesc: "अधिसूचित फसलों की विफलता के मामले में किसानों को बीमा कवरेज और वित्तीय सहायता।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** Financial support for crop loss due to natural calamities.\n• **Documents:** Land record (Patta), Sowing certificate.\n• **Portal:** pmfby.gov.in",
    hindiDetails: "• **लाभ:** प्राकृतिक आपदाओं के कारण फसल नुकसान के लिए वित्तीय सहायता।\n• **दस्तावेज:** भूमि रिकॉर्ड (पट्टा), बुवाई प्रमाण पत्र।",
    launchYear: "2016",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Agriculture, GoI"]
  },
  {
    id: 31,
    name: "National Apprenticeship Promotion Scheme (NAPS)",
    hindiName: "राष्ट्रीय शिक्षुता प्रोत्साहन योजना",
    type: "Central",
    categoryHeading: "🎓 Apprenticeship Training",
    hindiCategoryHeading: "🎓 अप्रेंटिसशिप ट्रेनिंग",
    desc: "Promoting apprenticeship training and increasing the engagement of apprentices in industries.",
    hindiDesc: "शिक्षुता प्रशिक्षण को बढ़ावा देना और उद्योगों में प्रशिक्षुओं की भागीदारी बढ़ाना।",
    minAge: 14,
    maxAge: 35,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Student", "Unemployed"],
    details: "• **Benefit:** Monthly stipend during training in private/public sector.\n• **Documents:** Educational certificates, Aadhaar.\n• **Portal:** apprenticeshipindia.gov.in",
    hindiDetails: "• **लाभ:** निजी/सार्वजनिक क्षेत्र में ट्रेनिंग के दौरान मासिक वजीफा।\n• **दस्तावेज:** शैक्षणिक प्रमाण पत्र, आधार।",
    launchYear: "2016",
    lastVerified: "March 15, 2026",
    sources: ["MSDE, GoI"]
  },
  {
    id: 32,
    name: "PM Mudra Yojana (PMMY)",
    hindiName: "प्रधानमंत्री मुद्रा योजना",
    type: "Central",
    categoryHeading: "💰 Small Business Loans",
    hindiCategoryHeading: "💰 मुद्रा ऋण (बिजनेस)",
    desc: "Loans up to ₹10 Lakh to non-corporate, non-farm small/micro enterprises.",
    hindiDesc: "गैर-कॉर्पोरेट, गैर-कृषि लघु/सूक्ष्म उद्यमों को ₹10 लाख तक का ऋण।",
    minAge: 18,
    maxAge: 65,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Shishu (up to ₹50k), Kishore (up to ₹5L), Tarun (up to ₹10L) loans.\n• **Documents:** Business proof, ID proof, Address proof.\n• **Portal:** Any commercial bank or MFI.",
    hindiDetails: "• **लाभ:** शिशु, किशोर और तरुण श्रेणियों में ₹10 लाख तक का ऋण।\n• **दस्तावेज:** बिजनेस प्रूफ, आईडी प्रूफ, निवास प्रमाण।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Finance, GoI"]
  },
  {
    id: 33,
    name: "Mukhyamantri Sukha Rahat Yojana",
    hindiName: "मुख्यमंत्री सुखा राहत योजना",
    type: "State",
    categoryHeading: "🌦️ Drought Relief",
    hindiCategoryHeading: "🌦️ सूखा राहत",
    desc: "One-time financial assistance to farmers in drought-affected blocks of Jharkhand.",
    hindiDesc: "झारखंड के सूखा प्रभावित ब्लॉकों में किसानों को एकमुश्त वित्तीय सहायता।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    occupation: ["Farmer"],
    details: "• **Benefit:** One-time grant of ₹3,500 per affected farmer family.\n• **Documents:** Aadhaar, Farmer Registration, Bank Passbook.\n• **Portal:** msry.jharkhand.gov.in",
    hindiDetails: "• **लाभ:** प्रभावित किसान परिवार को ₹3,500 की एकमुश्त सहायता।\n• **दस्तावेज:** आधार, किसान पंजीकरण, बैंक पासबुक।",
    launchYear: "2022",
    lastVerified: "March 15, 2026",
    sources: ["Agriculture Dept, Jharkhand"]
  },
  {
    id: 34,
    name: "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
    hindiName: "प्रधानमंत्री सुरक्षा बीमा योजना",
    type: "Central",
    categoryHeading: "🛡️ Accidental Insurance",
    hindiCategoryHeading: "🛡️ दुर्घटना बीमा",
    desc: "One-year accidental insurance scheme renewable from year to year for death or disability.",
    hindiDesc: "मृत्यु या विकलांगता के लिए साल-दर-साल नवीकरणीय एक वर्षीय दुर्घटना बीमा योजना।",
    minAge: 18,
    maxAge: 70,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** ₹2 Lakh cover at a very low premium of ₹20 per year.\n• **Documents:** Bank Account linked with Aadhaar.\n• **Portal:** Any bank branch.",
    hindiDetails: "• **लाभ:** ₹20 प्रति वर्ष के प्रीमियम पर ₹2 लाख का बीमा कवर।\n• **दस्तावेज:** आधार से जुड़ा बैंक खाता।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Finance, GoI"]
  },
  {
    id: 35,
    name: "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
    hindiName: "प्रधानमंत्री जीवन ज्योति बीमा योजना",
    type: "Central",
    categoryHeading: "🕊️ Life Insurance",
    hindiCategoryHeading: "🕊️ जीवन बीमा",
    desc: "One-year life insurance scheme renewable from year to year offering coverage for death due to any reason.",
    hindiDesc: "किसी भी कारण से मृत्यु होने पर कवरेज प्रदान करने वाली एक वर्षीय जीवन बीमा योजना।",
    minAge: 18,
    maxAge: 50,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** ₹2 Lakh life cover at ₹436 per year premium.\n• **Documents:** Bank Account, Aadhaar.\n• **Portal:** Any bank branch.",
    hindiDetails: "• **लाभ:** ₹436 प्रति वर्ष के प्रीमियम पर ₹2 लाख का जीवन बीमा।\n• **दस्तावेज:** बैंक खाता, आधार।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Finance, GoI"]
  },
  {
    id: 36,
    name: "Skill India Mission",
    hindiName: "स्किल इंडिया मिशन",
    type: "Central",
    categoryHeading: "🛠️ Vocational Training",
    hindiCategoryHeading: "🛠️ व्यवसायिक प्रशिक्षण",
    desc: "Empowering the youth of the country with skillsets to make them more employable.",
    hindiDesc: "देश के युवाओं को अधिक रोजगारपरक बनाने के लिए कौशल विकास के साथ सशक्त बनाना।",
    minAge: 15,
    maxAge: 45,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Student", "Unemployed"],
    details: "• **Benefit:** Certified short-term training across various sectors.\n• **Documents:** ID proof, Educational documents.\n• **Portal:** skillindia.gov.in",
    hindiDetails: "• **लाभ:** विभिन्न क्षेत्रों में प्रमाणित अल्पकालिक प्रशिक्षण।\n• **दस्तावेज:** पहचान पत्र, शैक्षणिक दस्तावेज।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["MSDE, GoI"]
  },
  {
    id: 37,
    name: "JAL JEEVAN MISSION",
    hindiName: "जल जीवन मिशन",
    type: "Central",
    categoryHeading: "🚰 Water Supply",
    hindiCategoryHeading: "🚰 जल आपूर्ति (नल से जल)",
    desc: "Ensuring functional household tap connection to every rural household.",
    hindiDesc: "प्रत्येक ग्रामीण परिवार को कार्यात्मक घरेलू नल कनेक्शन सुनिश्चित करना।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    details: "• **Benefit:** Safe and adequate drinking water through individual tap connections.\n• **Documents:** Address proof, Aadhaar.\n• **Portal:** jaljeevanmission.gov.in",
    hindiDetails: "• **लाभ:** व्यक्तिगत नल कनेक्शन के माध्यम से सुरक्षित पेयजल।\n• **दस्तावेज:** निवास प्रमाण, आधार।",
    launchYear: "2019",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Jal Shakti, GoI"]
  },
  {
    id: 38,
    name: "Mukhyamantri Vidya Laxmi Yojana",
    hindiName: "मुख्यमंत्री विद्या लक्ष्मी योजना",
    type: "State",
    categoryHeading: "👧 SC/ST Girl Education",
    hindiCategoryHeading: "👧 SC/ST बालिका शिक्षा",
    desc: "Promoting primary education among SC and ST girls and reducing dropout rates.",
    hindiDesc: "SC और ST लड़कियों के बीच प्राथमिक शिक्षा को बढ़ावा देना और ड्रॉपआउट दर को कम करना।",
    minAge: 5,
    maxAge: 14,
    gender: "Female",
    maxIncome: 9999999,
    categories: ["SC", "ST"],
    occupation: ["Student"],
    details: "• **Benefit:** ₹2,000 fixed deposit in the name of the girl child completing 5th grade.\n• **Documents:** School certificate, Caste certificate.\n• **Portal:** Apply via Primary School.",
    hindiDetails: "• **लाभ:** 5वीं कक्षा पूरी करने पर बालिका के नाम पर ₹2,000 की सावधि जमा।\n• **दस्तावेज:** स्कूल प्रमाण पत्र, जाति प्रमाण पत्र।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["Education Dept, Jharkhand"]
  },
  {
    id: 39,
    name: "Mukhyamantri Medha Chatravriti Yojana",
    hindiName: "मुख्यमंत्री मेधा छात्रवृत्ति योजना",
    type: "State",
    categoryHeading: "🎓 Merit Scholarship",
    hindiCategoryHeading: "🎓 मेधा छात्रवृत्ति",
    desc: "Scholarship for meritorious students of class 9 to 12 in Jharkhand government schools.",
    hindiDesc: "झारखंड के सरकारी स्कूलों में कक्षा 9 से 12 के मेधावी छात्रों के लिए छात्रवृत्ति।",
    minAge: 13,
    maxAge: 18,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Student"],
    details: "• **Benefit:** ₹12,000 per year for 4 years.\n• **Documents:** Class 8 marksheet, School certificate, Bank details.\n• **Portal:** JAC Board Jharkhand.",
    hindiDetails: "• **लाभ:** 4 वर्षों तक प्रति वर्ष ₹12,000।\n• **दस्तावेज:** कक्षा 8 की मार्कशीट, स्कूल प्रमाण पत्र।",
    launchYear: "2022",
    lastVerified: "March 15, 2026",
    sources: ["School Education & Literacy Dept, Jharkhand"]
  },
  {
    id: 40,
    name: "Jharkhand Mukhyamantri Kalakar Samman Yojana",
    hindiName: "झारखंड मुख्यमंत्री कलाकार सम्मान योजना",
    type: "State",
    categoryHeading: "🎨 Artist Welfare",
    hindiCategoryHeading: "🎨 कलाकार सम्मान",
    desc: "Monthly honorarium for senior and prominent artists of Jharkhand.",
    hindiDesc: "झारखंड के वरिष्ठ और प्रमुख कलाकारों के लिए मासिक मानदेय।",
    minAge: 60,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Artist", "Musician", "Writer", "Dancer"],
    details: "• **Benefit:** ₹4,000 per month honorarium.\n• **Documents:** Artist contribution proof, Aadhaar, Bank Details.\n• **Portal:** Art & Culture Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** ₹4,000 प्रति माह मानदेय।\n• **दस्तावेज:** कलाकार होने का प्रमाण, आधार।",
    launchYear: "2018",
    lastVerified: "March 15, 2026",
    sources: ["Tourism, Art & Culture Dept, Jharkhand"]
  },
  {
    id: 41,
    name: "Mukhyamantri Krishi Ashirwad Yojana (MKAY)",
    hindiName: "मुख्यमंत्री कृषि आशीर्वाद योजना",
    type: "State",
    categoryHeading: "🚜 Direct Benefit for Farmers",
    hindiCategoryHeading: "🚜 किसानों के लिए आशीर्वाद",
    desc: "Direct cash transfer to small and marginal farmers based on land area.",
    hindiDesc: "भूमि क्षेत्र के आधार पर लघु और सीमांत किसानों को सीधा नकद हस्तांतरण।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** ₹5,000 per acre (max ₹25,000) directly to bank account.\n• **Documents:** Land possession certificate (LPC), Aadhaar, Bank Passbook.\n• **Portal:** mkay.jharkhand.gov.in",
    hindiDetails: "• **लाभ:** ₹5,000 प्रति एकड़ (अधिकतम ₹25,000) सीधे बैंक खाते में।\n• **दस्तावेज:** भूमि प्रमाण पत्र (LPC), आधार।",
    launchYear: "2019",
    lastVerified: "March 15, 2026",
    sources: ["Agriculture Dept, Jharkhand"]
  },
  {
    id: 42,
    name: "Jharkhand Mukhyamantri Rozgar Protsahan Yojana",
    hindiName: "झारखंड मुख्यमंत्री रोजगार प्रोत्साहन योजना",
    type: "State",
    categoryHeading: "💼 Unemployment Allowance",
    hindiCategoryHeading: "💼 बेरोजगारी भत्ता",
    desc: "One-time annual financial assistance to educated unemployed youth of Jharkhand.",
    hindiDesc: "झारखंड के शिक्षित बेरोजगार युवाओं को एकमुश्त वार्षिक वित्तीय सहायता।",
    minAge: 18,
    maxAge: 35,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Unemployed"],
    details: "• **Benefit:** ₹5,000 (General) and ₹7,500 (SC/ST/Disabled) annually.\n• **Documents:** Educational certificates, Employment Exchange registration.\n• **Portal:** Jharkhand Employment Portal.",
    hindiDetails: "• **लाभ:** ₹5,000 से ₹7,500 वार्षिक सहायता।\n• **दस्तावेज:** शैक्षणिक प्रमाण पत्र, रोजगार विनिमय पंजीकरण।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["Labour & Employment Dept, Jharkhand"]
  },
  {
    id: 43,
    name: "Mukhyamantri Gambhir Bimari Upchar Yojana",
    hindiName: "मुख्यमंत्री गंभीर बीमारी उपचार योजना",
    type: "State",
    categoryHeading: "🏥 Critical Illness Support",
    hindiCategoryHeading: "🏥 गंभीर बीमारी उपचार",
    desc: "Financial assistance for the treatment of critical diseases like cancer and kidney failure.",
    hindiDesc: "कैंसर और किडनी फेलियर जैसी गंभीर बीमारियों के इलाज के लिए वित्तीय सहायता।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 800000,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Up to ₹5 Lakh to ₹10 Lakh for specialized treatment.\n• **Documents:** Disease certificate from recognized hospital, Income certificate.\n• **Portal:** Apply via Civil Surgeon Office.",
    hindiDetails: "• **लाभ:** ₹5 लाख से ₹10 लाख तक की सहायता।\n• **दस्तावेज:** अस्पताल का प्रमाण पत्र, आय प्रमाण पत्र।",
    launchYear: "2011",
    lastVerified: "March 15, 2026",
    sources: ["Health Dept, Jharkhand"]
  },
  {
    id: 44,
    name: "Pre-Matric Scholarship Jharkhand",
    hindiName: "प्री-मैट्रिक छात्रवृत्ति झारखंड",
    type: "State",
    categoryHeading: "📚 School Education Support",
    hindiCategoryHeading: "📚 स्कूली शिक्षा सहायता",
    desc: "Scholarship for SC, ST, and OBC students studying in classes 1 to 10.",
    hindiDesc: "कक्षा 1 से 10 में पढ़ने वाले एससी, एसटी और ओबीसी छात्रों के लिए छात्रवृत्ति।",
    minAge: 6,
    maxAge: 16,
    gender: "Any",
    maxIncome: 250000,
    categories: ["SC", "ST", "OBC"],
    occupation: ["Student"],
    details: "• **Benefit:** Annual scholarship amount based on class and category.\n• **Documents:** School certificate, Caste certificate, Bank details.\n• **Portal:** e-Kalyan Portal Jharkhand.",
    hindiDetails: "• **लाभ:** कक्षा के आधार पर वार्षिक छात्रवृत्ति राशि।\n• **दस्तावेज:** स्कूल प्रमाण पत्र, जाति प्रमाण पत्र।",
    launchYear: "2013",
    lastVerified: "March 15, 2026",
    sources: ["Welfare Dept, Jharkhand"]
  },
  {
    id: 45,
    name: "Post-Matric Scholarship for Minorities",
    hindiName: "अल्पसंख्यकों के लिए पोस्ट-मैट्रिक छात्रवृत्ति",
    type: "Central",
    categoryHeading: "🕌 Minority Welfare",
    hindiCategoryHeading: "🕌 अल्पसंख्यक कल्याण",
    desc: "Scholarship for students from minority communities for post-matric studies.",
    hindiDesc: "अल्पसंख्यक समुदायों के छात्रों के लिए मैट्रिक के बाद की पढ़ाई के लिए छात्रवृत्ति।",
    minAge: 15,
    maxAge: 35,
    gender: "Any",
    maxIncome: 200000,
    categories: ["Minority"],
    occupation: ["Student"],
    details: "• **Benefit:** Tuition fee + maintenance allowance.\n• **Documents:** Minority certificate, Income certificate, Previous marksheet.\n• **Portal:** National Scholarship Portal (NSP).",
    hindiDetails: "• **लाभ:** शिक्षण शुल्क + रखरखाव भत्ता।\n• **दस्तावेज:** अल्पसंख्यक प्रमाण पत्र, आय प्रमाण पत्र।",
    launchYear: "2006",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Minority Affairs, GoI"]
  },
  {
    id: 46,
    name: "PM-PRANAM Scheme",
    hindiName: "पीएम-प्रणाम योजना",
    type: "Central",
    categoryHeading: "🌱 Sustainable Agriculture",
    hindiCategoryHeading: "🌱 सतत कृषि सहायता",
    desc: "Promoting balanced use of chemical fertilizers and alternative fertilizers for soil health.",
    hindiDesc: "मिट्टी के स्वास्थ्य के लिए रासायनिक उर्वरकों के संतुलित उपयोग और वैकल्पिक उर्वरकों को बढ़ावा देना।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** Incentive for adopting bio-fertilizers and organic farming.\n• **Documents:** Land records, Soil health card.\n• **Portal:** Agriculture Dept Portal.",
    hindiDetails: "• **लाभ:** जैव-उर्वरकों को अपनाने के लिए प्रोत्साहन।\n• **दस्तावेज:** भूमि रिकॉर्ड, मृदा स्वास्थ्य कार्ड।",
    launchYear: "2023",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Chemicals and Fertilizers, GoI"]
  },
  {
    id: 47,
    name: "One-Stop Centre Scheme (Sakhi)",
    hindiName: "वन-स्टॉप सेंटर योजना (सखी)",
    type: "Central",
    categoryHeading: "🛡️ Women Safety",
    hindiCategoryHeading: "🛡️ महिला सुरक्षा (सखी केंद्र)",
    desc: "Support for women affected by violence with medical, legal, and psychological aid.",
    hindiDesc: "चिकित्सा, कानूनी और मनोवैज्ञानिक सहायता के साथ हिंसा से प्रभावित महिलाओं के लिए समर्थन।",
    minAge: 0,
    maxAge: 99,
    gender: "Female",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Emergency shelter and counseling for women in distress.\n• **Documents:** Any identity proof (if available).\n• **Portal:** District Sakhi Centres.",
    hindiDetails: "• **लाभ:** संकट में महिलाओं के लिए आपातकालीन आश्रय और परामर्श।\n• **दस्तावेज:** कोई भी पहचान पत्र।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of WCD, GoI"]
  },
  {
    id: 48,
    name: "PM Van Dhan Yojana",
    hindiName: "पीएम वन धन योजना",
    type: "Central",
    categoryHeading: "🌲 Tribal Livelihood",
    hindiCategoryHeading: "🌲 जनजातीय आजीविका",
    desc: "Value addition and marketing of Minor Forest Produce (MFP) by tribal gatherers.",
    hindiDesc: "जनजातीय संग्रहकर्ताओं द्वारा लघु वनोपज (MFP) का मूल्यवर्धन और विपणन।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["ST"],
    geography: "Rural",
    details: "• **Benefit:** Formation of Van Dhan Vikas Kendras for processing products.\n• **Documents:** Caste certificate, Residence proof.\n• **Portal:** TRIFED Portal.",
    hindiDetails: "• **लाभ:** उत्पादों के प्रसंस्करण के लिए वन धन विकास केंद्रों का गठन।\n• **दस्तावेज:** जाति प्रमाण पत्र।",
    launchYear: "2018",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Tribal Affairs, GoI"]
  },
  {
    id: 49,
    name: "Garib Kalyan Rojgar Abhiyaan",
    hindiName: "गरीब कल्याण रोजगार अभियान",
    type: "Central",
    categoryHeading: "👷 Migrant Worker Support",
    hindiCategoryHeading: "👷 प्रवासी श्रमिक रोजगार",
    desc: "Providing immediate employment opportunities to returnee migrant workers.",
    hindiDesc: "वापस लौटे प्रवासी श्रमिकों को तत्काल रोजगार के अवसर प्रदान करना।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Worker", "Labourer"],
    details: "• **Benefit:** Employment in public works like road, housing, and water conservation.\n• **Documents:** Job card, Aadhaar.\n• **Portal:** District Block Office.",
    hindiDetails: "• **लाभ:** सड़क और आवास जैसे सार्वजनिक कार्यों में रोजगार।\n• **दस्तावेज:** जॉब कार्ड, आधार।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Rural Development, GoI"]
  },
  {
    id: 50,
    name: "PM-KUSUM Scheme",
    hindiName: "पीएम-कुसुम योजना",
    type: "Central",
    categoryHeading: "☀️ Solar Energy for Farmers",
    hindiCategoryHeading: "☀️ सोलर पंप योजना",
    desc: "Providing standalone solar pumps and solarization of existing grid-connected pumps.",
    hindiDesc: "स्टैंडअलोन सौर पंप प्रदान करना और मौजूदा ग्रिड से जुड़े पंपों का सोलराइजेशन।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** 60% subsidy on solar water pumps.\n• **Documents:** Land records, Aadhaar, Bank Details.\n• **Portal:** MNRE Solar Portal.",
    hindiDetails: "• **लाभ:** सोलर वाटर पंपों पर 60% की सब्सिडी।\n• **दस्तावेज:** भूमि रिकॉर्ड, आधार।",
    launchYear: "2019",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of New & Renewable Energy, GoI"]
  },
  {
    id: 51,
    name: "Mukhyamantri Jan-Van Yojana",
    hindiName: "मुख्यमंत्री जन-वन योजना",
    type: "State",
    categoryHeading: "🌳 Agro-Forestry",
    hindiCategoryHeading: "🌳 जन-वन (वृक्षारोपण)",
    desc: "Subsidy for plantation on private land to increase green cover and farmer income.",
    hindiDesc: "हरियाली बढ़ाने और किसानों की आय के लिए निजी भूमि पर वृक्षारोपण के लिए सब्सिडी।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    requires_land: true,
    details: "• **Benefit:** 75% subsidy on cost of saplings and maintenance for 3 years.\n• **Documents:** Land documents, Aadhaar.\n• **Portal:** Forest Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** 3 वर्षों तक पौधों और रखरखाव की लागत पर 75% सब्सिडी।\n• **दस्तावेज:** जमीन के कागज।",
    launchYear: "2016",
    lastVerified: "March 15, 2026",
    sources: ["Forest Dept, Jharkhand"]
  },
  {
    id: 52,
    name: "National Career Service (NCS)",
    hindiName: "राष्ट्रीय करियर सेवा",
    type: "Central",
    categoryHeading: "💼 Job Matchmaking",
    hindiCategoryHeading: "💼 नौकरी सहायता पोर्टल",
    desc: "A digital portal that provides a wide range of employment and career-related services.",
    hindiDesc: "एक डिजिटल पोर्टल जो रोजगार और करियर से संबंधित सेवाओं की एक विस्तृत श्रृंखला प्रदान करता है।",
    minAge: 18,
    maxAge: 60,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Unemployed", "Student"],
    details: "• **Benefit:** Access to job vacancies, career counseling, and skill training.\n• **Documents:** Educational certificates, Aadhaar.\n• **Portal:** ncs.gov.in",
    hindiDetails: "• **लाभ:** नौकरी की रिक्तियों और करियर परामर्श तक पहुंच।\n• **दस्तावेज:** शैक्षणिक प्रमाण पत्र।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Labour and Employment, GoI"]
  },
  {
    id: 53,
    name: "PM Matsya Sampada Yojana",
    hindiName: "पीएम मत्स्य संपदा योजना",
    type: "Central",
    categoryHeading: "🐟 Fisheries Support",
    hindiCategoryHeading: "🐟 मछली पालन सहायता",
    desc: "Financial assistance for sustainable development of the fisheries sector.",
    hindiDesc: "मत्स्य पालन क्षेत्र के सतत विकास के लिए वित्तीय सहायता।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Fisherman", "Farmer"],
    details: "• **Benefit:** Subsidy for pond construction, fish seed, and equipment.\n• **Documents:** Aadhaar, Land record (for ponds), Bank Details.\n• **Portal:** pmmsy.nic.in",
    hindiDetails: "• **लाभ:** तालाब निर्माण और मछली बीज के लिए सब्सिडी।\n• **दस्तावेज:** आधार, जमीन के कागज।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["Department of Fisheries, GoI"]
  },
  {
    id: 54,
    name: "Jharkhand Mukhyamantri Kisan Pathshala",
    hindiName: "झारखंड मुख्यमंत्री किसान पाठशाला",
    type: "State",
    categoryHeading: "🏫 Agriculture Education",
    hindiCategoryHeading: "🏫 किसान पाठशाला",
    desc: "Training centers for farmers to learn modern agriculture techniques and technology.",
    hindiDesc: "किसानों के लिए आधुनिक कृषि तकनीकों और प्रौद्योगिकी को सीखने के लिए प्रशिक्षण केंद्र।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Farmer"],
    details: "• **Benefit:** Hands-on training and exposure visits to advanced farms.\n• **Documents:** Farmer ID, Aadhaar.\n• **Portal:** District Agriculture Dept.",
    hindiDetails: "• **लाभ:** आधुनिक कृषि तकनीकों पर व्यावहारिक प्रशिक्षण।\n• **दस्तावेज:** किसान आईडी, आधार।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Agriculture Dept, Jharkhand"]
  },
  {
    id: 55,
    name: "PM-WANI (Wi-Fi Access Network Interface)",
    hindiName: "पीएम-वाणी योजना",
    type: "Central",
    categoryHeading: "🌐 Public Wi-Fi",
    hindiCategoryHeading: "🌐 सार्वजनिक वाई-फाई",
    desc: "Increasing broadband penetration through public Wi-Fi hotspots across the country.",
    hindiDesc: "पूरे देश में सार्वजनिक वाई-फाई हॉटस्पॉट के माध्यम से ब्रॉडबैंड प्रसार बढ़ाना।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Low-cost high-speed internet in public places.\n• **Documents:** Mobile number for OTP registration.\n• **Portal:** PM-WANI Central Registry.",
    hindiDetails: "• **लाभ:** सार्वजनिक स्थानों पर कम लागत वाला हाई-स्पीड इंटरनेट।\n• **दस्तावेज:** ओटीपी के लिए मोबाइल नंबर।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["Department of Telecom, GoI"]
  },
  {
    id: 56,
    name: "Jharkhand Sahay Yojana",
    hindiName: "झारखंड सहाय योजना",
    type: "State",
    categoryHeading: "🏆 Sports for Youth",
    hindiCategoryHeading: "🏆 खेलों को बढ़ावा (सहाय)",
    desc: "Promoting sports culture among youth in Left Wing Extremism (LWE) affected areas.",
    hindiDesc: "उग्रवाद प्रभावित क्षेत्रों में युवाओं के बीच खेल संस्कृति को बढ़ावा देना।",
    minAge: 14,
    maxAge: 19,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Organizing sports competitions and nurturing talent.\n• **Documents:** School ID, Domicile proof.\n• **Portal:** Sports Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** खेल प्रतियोगिताओं का आयोजन और प्रतिभा को निखारना।\n• **दस्तावेज:** स्कूल आईडी, निवास प्रमाण।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Sports & Youth Affairs Dept, Jharkhand"]
  },
  {
    id: 57,
    name: "PM-ABHIM (Ayushman Bharat Health Infrastructure Mission)",
    hindiName: "पीएम-अभिम योजना",
    type: "Central",
    categoryHeading: "🏥 Healthcare Infrastructure",
    hindiCategoryHeading: "🏥 स्वास्थ्य बुनियादी ढांचा",
    desc: "Strengthening health infrastructure and primary health centers in rural and urban areas.",
    hindiDesc: "ग्रामीण और शहरी क्षेत्रों में स्वास्थ्य बुनियादी ढांचे और प्राथमिक स्वास्थ्य केंद्रों को मजबूत करना।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Improved health facilities and diagnostics in local blocks.\n• **Documents:** Aadhaar Card.\n• **Portal:** Ministry of Health, GoI.",
    hindiDetails: "• **लाभ:** स्थानीय ब्लॉकों में बेहतर स्वास्थ्य सुविधाएं और डायग्नोस्टिक्स।\n• **दस्तावेज:** आधार कार्ड।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Health, GoI"]
  },
  {
    id: 58,
    name: "Mukhyamantri Rozgar Srijan Yojana (Subsidy Extension)",
    hindiName: "मुख्यमंत्री रोजगार सृजन योजना (सब्सिडी विस्तार)",
    type: "State",
    categoryHeading: "💼 Self-Employment Boost",
    hindiCategoryHeading: "💼 स्वरोजगार (अतिरिक्त सब्सिडी)",
    desc: "Extended subsidy for youth taking loans for commercial transport and self-employment.",
    hindiDesc: "वाणिज्यिक परिवहन और स्वरोजगार के लिए ऋण लेने वाले युवाओं के लिए विस्तारित सब्सिडी।",
    minAge: 18,
    maxAge: 45,
    gender: "Any",
    maxIncome: 500000,
    categories: ["SC", "ST", "OBC", "Minority"],
    details: "• **Benefit:** 40% subsidy or ₹5 Lakh (whichever is less) on business loans.\n• **Documents:** Project report, Domicile certificate, Bank Account.\n• **Portal:** Welfare Dept District Office.",
    hindiDetails: "• **लाभ:** बिजनेस लोन पर 40% या ₹5 लाख तक की सब्सिडी।\n• **दस्तावेज:** प्रोजेक्ट रिपोर्ट, निवास प्रमाण।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Welfare Dept, Jharkhand"]
  },
  {
    id: 59,
    name: "Mukhyamantri Pashu-Dhan Vikas Yojana",
    hindiName: "मुख्यमंत्री पशुधन विकास योजना",
    type: "State",
    categoryHeading: "🐄 Livestock Development",
    hindiCategoryHeading: "🐄 पशुधन विकास",
    desc: "Subsidy on livestock like cows, goats, and poultry to increase rural income.",
    hindiDesc: "ग्रामीण आय बढ़ाने के लिए गाय, बकरी और मुर्गी जैसे पशुधन पर सब्सिडी।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Farmer", "Worker"],
    details: "• **Benefit:** 50% to 90% subsidy on purchase of livestock.\n• **Documents:** Aadhaar, Caste certificate, Bank passbook.\n• **Portal:** Animal Husbandry Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** पशुधन की खरीद पर 50% से 90% तक की सब्सिडी।\n• **दस्तावेज:** आधार, जाति प्रमाण पत्र।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Animal Husbandry Dept, Jharkhand"]
  },
  {
    id: 60,
    name: "Jharkhand Mukhyamantri Gram Gadi Yojana",
    hindiName: "झारखंड मुख्यमंत्री ग्राम गाड़ी योजना",
    type: "State",
    categoryHeading: "🚌 Rural Transport",
    hindiCategoryHeading: "🚌 ग्राम गाड़ी योजना",
    desc: "Providing free or subsidized bus travel for students, elderly, and disabled in rural areas.",
    hindiDesc: "ग्रामीण क्षेत्रों में छात्रों, बुजुर्गों और विकलांगों के लिए मुफ्त या रियायती बस यात्रा।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    details: "• **Benefit:** Free travel for specific categories; improved connectivity.\n• **Documents:** Identity proof, Category certificate (for students/elderly).\n• **Portal:** Transport Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** विशिष्ट श्रेणियों के लिए मुफ्त यात्रा; बेहतर कनेक्टिविटी।\n• **दस्तावेज:** पहचान पत्र, श्रेणी प्रमाण पत्र।",
    launchYear: "2023",
    lastVerified: "March 15, 2026",
    sources: ["Transport Dept, Jharkhand"]
  },
  {
    id: 61,
    name: "Birsa Harit Gram Yojana",
    hindiName: "बिरसा हरित ग्राम योजना",
    type: "State",
    categoryHeading: "🌳 Sustainable Livelihood",
    hindiCategoryHeading: "🌳 बिरसा हरित ग्राम",
    desc: "Planting fruit-bearing trees on fallow land to create long-term assets for rural families.",
    hindiDesc: "ग्रामीण परिवारों के लिए दीर्घकालिक संपत्ति बनाने के लिए परती भूमि पर फलदार पेड़ लगाना।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["SC", "ST"],
    requires_land: true,
    details: "• **Benefit:** Financial support for plantation and maintenance via MGNREGA.\n• **Documents:** Land record, MGNREGA Job card.\n• **Portal:** Rural Development Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** वृक्षारोपण और रखरखाव के लिए मनरेगा के माध्यम से वित्तीय सहायता।\n• **दस्तावेज:** जमीन के कागज, मनरेगा जॉब कार्ड।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["Rural Development Dept, Jharkhand"]
  },
  {
    id: 62,
    name: "PM SVANidhi",
    hindiName: "पीएम स्वनिधि योजना",
    type: "Central",
    categoryHeading: "🧺 Street Vendor Support",
    hindiCategoryHeading: "🧺 रेहड़ी-पटरी सहायता",
    desc: "Collateral-free working capital loan for street vendors to restart their businesses.",
    hindiDesc: "स्ट्रीट वेंडरों को अपना व्यवसाय फिर से शुरू करने के लिए संपार्श्विक-मुक्त कार्यशील पूंजी ऋण।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Worker"],
    details: "• **Benefit:** First loan up to ₹10,000, subsequent loans up to ₹50,000.\n• **Documents:** Aadhaar, Vending certificate (LoR).\n• **Portal:** pmsvanidhi.mohua.gov.in",
    hindiDetails: "• **लाभ:** ₹10,000 तक का प्रारंभिक ऋण, समय पर भुगतान पर अधिक ऋण।\n• **दस्तावेज:** आधार, वेंडिंग प्रमाण पत्र।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["MoHUA, GoI"]
  },
  {
    id: 63,
    name: "PM-Vishwakarma Scheme",
    hindiName: "पीएम-विश्वकर्मा योजना",
    type: "Central",
    categoryHeading: "🔨 Artisan Support",
    hindiCategoryHeading: "🔨 विश्वकर्मा योजना",
    desc: "Support for traditional artisans and craftspeople with skill training and low-interest loans.",
    hindiDesc: "पारंपरिक कारीगरों और शिल्पकारों को कौशल प्रशिक्षण और कम ब्याज वाले ऋण के साथ सहायता।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Artisan", "Worker"],
    details: "• **Benefit:** Stipend for training, toolkits worth ₹15,000, and collateral-free loans.\n• **Documents:** Aadhaar, Ration card, Proof of craft.\n• **Portal:** pmvishwakarma.gov.in",
    hindiDetails: "• **लाभ:** प्रशिक्षण वजीफा, ₹15,000 का टूलकिट और आसान ऋण।\n• **दस्तावेज:** आधार, शिल्प का प्रमाण।",
    launchYear: "2023",
    lastVerified: "March 15, 2026",
    sources: ["MSME, GoI"]
  },
  {
    id: 64,
    name: "Jharkhand Mukhyamantri Balika Cycle Yojana",
    hindiName: "झारखंड मुख्यमंत्री बालिका साइकिल योजना",
    type: "State",
    categoryHeading: "🚲 Girl Education Support",
    hindiCategoryHeading: "🚲 बालिका साइकिल योजना",
    desc: "Providing funds for purchasing cycles for girl students to reduce dropout rates in high schools.",
    hindiDesc: "हाई स्कूलों में ड्रॉपआउट दर को कम करने के लिए छात्राओं को साइकिल खरीदने के लिए धन प्रदान करना।",
    minAge: 13,
    maxAge: 16,
    gender: "Female",
    maxIncome: 9999999,
    categories: ["SC", "ST", "OBC", "Minority"],
    occupation: ["Student"],
    details: "• **Benefit:** Direct cash transfer of ₹3,000 to ₹3,500 to buy a bicycle.\n• **Documents:** School certificate (Class 8th/9th), Caste certificate.\n• **Portal:** Apply via School Principal.",
    hindiDetails: "• **लाभ:** साइकिल खरीदने के लिए ₹3,500 तक का नकद हस्तांतरण।\n• **दस्तावेज:** स्कूल प्रमाण पत्र, जाति प्रमाण पत्र।",
    launchYear: "2002",
    lastVerified: "March 15, 2026",
    sources: ["Welfare Dept, Jharkhand"]
  },
  {
    id: 65,
    name: "Savitribai Phule Kishori Samriddhi Yojana",
    hindiName: "सावित्रीबाई फुले किशोरी समृद्धि योजना",
    type: "State",
    categoryHeading: "👧 Adolescent Girl Welfare",
    hindiCategoryHeading: "👧 किशोरी समृद्धि",
    desc: "Financial assistance to adolescent girls to promote education and prevent child marriage.",
    hindiDesc: "शिक्षा को बढ़ावा देने और बाल विवाह को रोकने के लिए किशोरियों को वित्तीय सहायता।",
    minAge: 13,
    maxAge: 19,
    gender: "Female",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Student"],
    details: "• **Benefit:** Total benefit of ₹40,000 across different classes and at age 18.\n• **Documents:** Aadhaar, School enrollment proof, Income certificate (if required).\n• **Portal:** District Social Welfare Office.",
    hindiDetails: "• **लाभ:** विभिन्न कक्षाओं और 18 वर्ष की आयु में कुल ₹40,000 का लाभ।\n• **दस्तावेज:** आधार, स्कूल नामांकन प्रमाण।",
    launchYear: "2022",
    lastVerified: "March 15, 2026",
    sources: ["Social Welfare Dept, Jharkhand"]
  },
  {
    id: 66,
    name: "Jharkhand Mukhyamantri Shramik (MSY) Yojana",
    hindiName: "झारखंड मुख्यमंत्री श्रमिक योजना",
    type: "State",
    categoryHeading: "🏙️ Urban Employment",
    hindiCategoryHeading: "🏙️ मुख्यमंत्री श्रमिक योजना",
    desc: "Guaranteeing 100 days of employment in a financial year for urban unskilled workers.",
    hindiDesc: "शहरी अकुशल श्रमिकों के लिए एक वित्तीय वर्ष में 100 दिनों के रोजगार की गारंटी।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Urban",
    occupation: ["Worker", "Labourer"],
    details: "• **Benefit:** Minimum wages for 100 days; unemployment allowance if work not provided.\n• **Documents:** Aadhaar, Domicile of Urban area.\n• **Portal:** msy.jharkhand.gov.in",
    hindiDetails: "• **लाभ:** 100 दिनों का रोजगार; काम न मिलने पर बेरोजगारी भत्ता।\n• **दस्तावेज:** आधार, शहरी निवास प्रमाण।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["UDD, Jharkhand"]
  },
  {
    id: 67,
    name: "PM-Surya Ghar: Muft Bijli Yojana",
    hindiName: "पीएम-सूर्य घर: मुफ्त बिजली योजना",
    type: "Central",
    categoryHeading: "☀️ Rooftop Solar",
    hindiCategoryHeading: "☀️ सूर्य घर योजना",
    desc: "Subsidy for installing rooftop solar panels to provide up to 300 units of free electricity per month.",
    hindiDesc: "प्रति माह 300 यूनिट तक मुफ्त बिजली प्रदान करने के लिए रूफटॉप सोलर पैनल लगाने के लिए सब्सिडी।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Subsidy of ₹30,000 to ₹78,000 depending on system capacity.\n• **Documents:** Electricity bill, Property documents, Aadhaar.\n• **Portal:** pmsuryaghar.gov.in",
    hindiDetails: "• **लाभ:** सोलर सिस्टम पर ₹78,000 तक की सब्सिडी और मुफ्त बिजली।\n• **दस्तावेज:** बिजली बिल, आधार।",
    launchYear: "2024",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of New & Renewable Energy, GoI"]
  },
  {
    id: 68,
    name: "Jharkhand Mukhyamantri Sarvajan Pension Yojana",
    hindiName: "झारखंड मुख्यमंत्री सर्वजन पेंशन योजना",
    type: "State",
    categoryHeading: "👵 Universal Pension",
    hindiCategoryHeading: "👵 सर्वजन पेंशन",
    desc: "Monthly pension for all elderly, widows, and disabled persons without any income cap (universal).",
    hindiDesc: "बिना किसी आय सीमा के सभी बुजुर्गों, विधवाओं और विकलांग व्यक्तियों के लिए मासिक पेंशन।",
    minAge: 60,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** ₹1,000 per month directly to bank account.\n• **Documents:** Aadhaar, Bank passbook, Age proof.\n• **Portal:** Block Development Office.",
    hindiDetails: "• **लाभ:** ₹1,000 प्रति माह सीधे बैंक खाते में।\n• **दस्तावेज:** आधार, आयु प्रमाण पत्र।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Social Welfare Dept, Jharkhand"]
  },
  {
    id: 69,
    name: "PM-eBus Sewa",
    hindiName: "पीएम-ईबस सेवा",
    type: "Central",
    categoryHeading: "⚡ Electric Mobility",
    hindiCategoryHeading: "⚡ ई-बस सेवा",
    desc: "Deployment of electric buses in cities to promote sustainable and clean urban transport.",
    hindiDesc: "स्थायी और स्वच्छ शहरी परिवहन को बढ़ावा देने के लिए शहरों में इलेक्ट्रिक बसों की तैनाती।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Urban",
    details: "• **Benefit:** Improved public transport with zero emission.\n• **Documents:** Not required for travel.\n• **Portal:** Ministry of Housing and Urban Affairs.",
    hindiDetails: "• **लाभ:** बिना प्रदूषण के बेहतर सार्वजनिक परिवहन।\n• **दस्तावेज:** यात्रा के लिए आवश्यक नहीं।",
    launchYear: "2023",
    lastVerified: "March 15, 2026",
    sources: ["MoHUA, GoI"]
  },
  {
    id: 70,
    name: "Mukhyamantri Jal Nal Yojana",
    hindiName: "मुख्यमंत्री जल नल योजना",
    type: "State",
    categoryHeading: "🚰 State Water Supply",
    hindiCategoryHeading: "🚰 जल नल योजना",
    desc: "Complementary state scheme to provide piped drinking water to households not covered by central missions.",
    hindiDesc: "केंद्रीय मिशनों के दायरे में नहीं आने वाले घरों को पाइप से पेयजल उपलब्ध कराने की राज्य योजना।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Functional tap connection with safe drinking water.\n• **Documents:** Address proof, Aadhaar.\n• **Portal:** DWSD, Jharkhand.",
    hindiDetails: "• **लाभ:** सुरक्षित पेयजल के साथ कार्यात्मक नल कनेक्शन।\n• **दस्तावेज:** निवास प्रमाण, आधार।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["DWSD, Jharkhand"]
  },
  {
    id: 71,
    name: "Jharkhand Mukhyamantri Swasthya Bima Yojana",
    hindiName: "झारखंड मुख्यमंत्री स्वास्थ्य बीमा योजना",
    type: "State",
    categoryHeading: "🏥 State Health Cover",
    hindiCategoryHeading: "🏥 स्वास्थ्य बीमा",
    desc: "Additional health insurance for families not covered under Ayushman Bharat (PM-JAY).",
    hindiDesc: "आयुष्मान भारत (PM-JAY) के दायरे में नहीं आने वाले परिवारों के लिए अतिरिक्त स्वास्थ्य बीमा।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Cashless treatment up to ₹2 Lakh in empanelled hospitals.\n• **Documents:** Ration card, Aadhaar.\n• **Portal:** Health Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** सूचीबद्ध अस्पतालों में ₹2 लाख तक का कैशलेस इलाज।\n• **दस्तावेज:** राशन कार्ड, आधार।",
    launchYear: "2017",
    lastVerified: "March 15, 2026",
    sources: ["Health Dept, Jharkhand"]
  },
  {
    id: 72,
    name: "PM-Fasal Bima Yojana",
    hindiName: "प्रधानमंत्री फसल बीमा योजना",
    type: "Central",
    categoryHeading: "🌾 Crop Insurance",
    hindiCategoryHeading: "🌾 फसल बीमा",
    desc: "Comprehensive insurance for crops against natural calamities and pests.",
    hindiDesc: "प्राकृतिक आपदाओं और कीटों के खिलाफ फसलों के लिए व्यापक बीमा।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** Financial support to farmers in case of crop failure.\n• **Documents:** Land records, Sowing certificate, Aadhaar.\n• **Portal:** pmfby.gov.in",
    hindiDetails: "• **लाभ:** फसल खराब होने की स्थिति में किसानों को वित्तीय सहायता।\n• **दस्तावेज:** जमीन के कागज, बुवाई प्रमाण।",
    launchYear: "2016",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Agriculture, GoI"]
  },
  {
    id: 73,
    name: "Jharkhand Mukhyamantri Dal-Bhat Yojana",
    hindiName: "झारखंड मुख्यमंत्री दाल-भात योजना",
    type: "State",
    categoryHeading: "🍛 Food Security",
    hindiCategoryHeading: "🍛 दाल-भात योजना",
    desc: "Providing cooked meals (rice and pulses) at a very nominal rate of ₹5 per plate.",
    hindiDesc: "₹5 प्रति प्लेट की बहुत मामूली दर पर पका हुआ भोजन (चावल और दाल) प्रदान करना।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** Nutritious meal at ₹5 available at designated centres.\n• **Documents:** Not required for walk-in.\n• **Portal:** Food & Civil Supplies Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** ₹5 में पौष्टिक भोजन, निर्दिष्ट केंद्रों पर उपलब्ध।\n• **दस्तावेज:** आवश्यक नहीं।",
    launchYear: "2011",
    lastVerified: "March 15, 2026",
    sources: ["Food & Civil Supplies Dept, Jharkhand"]
  },
  {
    id: 74,
    name: "PM-Awas Yojana - Urban",
    hindiName: "प्रधानमंत्री आवास योजना - शहरी",
    type: "Central",
    categoryHeading: "🏙️ Urban Housing",
    hindiCategoryHeading: "🏙️ शहरी आवास",
    desc: "Providing affordable housing to the urban poor, including EWS and LIG categories.",
    hindiDesc: "EWS और LIG श्रेणियों सहित शहरी गरीबों को किफायती आवास प्रदान करना।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 1800000,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Urban",
    details: "• **Benefit:** Interest subsidy on home loans or direct financial assistance.\n• **Documents:** Income certificate, Aadhaar, Land ownership (if applying for BLC).\n• **Portal:** pmay-urban.gov.in",
    hindiDetails: "• **लाभ:** होम लोन पर ब्याज सब्सिडी या सीधी वित्तीय सहायता।\n• **दस्तावेज:** आय प्रमाण पत्र, आधार।",
    launchYear: "2015",
    lastVerified: "March 15, 2026",
    sources: ["MoHUA, GoI"]
  },
  {
    id: 75,
    name: "Jharkhand Mukhyamantri Shiksha Protsahan Yojana",
    hindiName: "झारखंड मुख्यमंत्री शिक्षा प्रोत्साहन योजना",
    type: "State",
    categoryHeading: "📚 Coaching for Competitive Exams",
    hindiCategoryHeading: "📚 प्रतियोगी परीक्षा कोचिंग",
    desc: "Free coaching for students from poor families for national competitive exams like JEE, NEET, and CLAT.",
    hindiDesc: "गरीब परिवारों के छात्रों के लिए JEE, NEET और CLAT जैसी राष्ट्रीय प्रतियोगी परीक्षाओं के लिए मुफ्त कोचिंग।",
    minAge: 15,
    maxAge: 20,
    gender: "Any",
    maxIncome: 250000,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Student"],
    details: "• **Benefit:** Free coaching at reputed institutes + ₹2,500 monthly stipend for lodging.\n• **Documents:** Class 10th marksheet, Income certificate, Caste certificate.\n• **Portal:** Higher Education Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** मुफ्त कोचिंग + आवास के लिए ₹2,500 मासिक वजीफा।\n• **दस्तावेज:** 10वीं की मार्कशीट, आय प्रमाण पत्र।",
    launchYear: "2022",
    lastVerified: "March 15, 2026",
    sources: ["Higher Education Dept, Jharkhand"]
  },
  {
    id: 76,
    name: "Eklavya Model Residential Schools (EMRS)",
    hindiName: "एकलव्य मॉडल आवासीय विद्यालय",
    type: "Central",
    categoryHeading: "🏫 Tribal Residential Education",
    hindiCategoryHeading: "🏫 एकलव्य विद्यालय",
    desc: "Providing quality middle and high-level education to ST students in remote areas.",
    hindiDesc: "दूरदराज के क्षेत्रों में एसटी छात्रों को गुणवत्तापूर्ण माध्यमिक और उच्च-स्तरीय शिक्षा प्रदान करना।",
    minAge: 10,
    maxAge: 18,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["ST"],
    occupation: ["Student"],
    details: "• **Benefit:** Free residential education from Class 6 to 12.\n• **Documents:** ST certificate, Birth certificate, Previous class result.\n• **Portal:** Ministry of Tribal Affairs / NESTS.",
    hindiDetails: "• **लाभ:** कक्षा 6 से 12 तक मुफ्त आवासीय शिक्षा।\n• **दस्तावेज:** एसटी प्रमाण पत्र, जन्म प्रमाण पत्र।",
    launchYear: "1997",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Tribal Affairs, GoI"]
  },
  {
    id: 77,
    name: "PM-POSHAN (Mid-Day Meal Support)",
    hindiName: "पीएम-पोषण (मध्याह्न भोजन)",
    type: "Central",
    categoryHeading: "🍱 Nutritional Support",
    hindiCategoryHeading: "🍱 मध्याह्न भोजन",
    desc: "Providing one hot cooked meal to children in government and government-aided schools.",
    hindiDesc: "सरकारी और सरकारी सहायता प्राप्त स्कूलों में बच्चों को एक गर्म पका हुआ भोजन प्रदान करना।",
    minAge: 5,
    maxAge: 14,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Student"],
    details: "• **Benefit:** Improved nutrition and increased school attendance.\n• **Documents:** School enrollment.\n• **Portal:** Ministry of Education, GoI.",
    hindiDetails: "• **लाभ:** बेहतर पोषण और स्कूल में उपस्थिति में वृद्धि।\n• **दस्तावेज:** स्कूल नामांकन।",
    launchYear: "1995",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Education, GoI"]
  },
  {
    id: 78,
    name: "Jharkhand Mukhyamantri Kanyadan Yojana",
    hindiName: "झारखंड मुख्यमंत्री कन्यादान योजना",
    type: "State",
    categoryHeading: "💍 Marriage Assistance",
    hindiCategoryHeading: "💍 कन्यादान योजना",
    desc: "Financial assistance for the marriage of girls from BPL families.",
    hindiDesc: "बीपीएल परिवारों की लड़कियों की शादी के लिए वित्तीय सहायता।",
    minAge: 18,
    maxAge: 35,
    gender: "Female",
    maxIncome: 72000,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** One-time grant of ₹30,000 for marriage expenses.\n• **Documents:** BPL card, Age proof of bride, Income certificate.\n• **Portal:** Social Welfare Dept, Jharkhand.",
    hindiDetails: "• **लाभ:** शादी के खर्च के लिए ₹30,000 की एकमुश्त सहायता।\n• **दस्तावेज:** बीपीएल कार्ड, आयु प्रमाण।",
    launchYear: "2004",
    lastVerified: "March 15, 2026",
    sources: ["Social Welfare Dept, Jharkhand"]
  }
];



