import { Scheme } from "./types";

export const SCHEMES_DB: Scheme[] = [ 
  { 
    id: 1, 
    name: "e-Kalyan Scholarship (Post-Matric)", 
    hindiName: "ई-कल्याण छात्रवृत्ति (मैट्रिकोत्तर)",
    type: "State",
    categoryHeading: "📚 Education Support", 
    hindiCategoryHeading: "📚 पढ़ाई के लिए (शिक्षा)",
    desc: "Financial assistance for students from SC, ST, and OBC categories.", 
    hindiDesc: "झारखंड सरकार और केंद्र सरकार की छात्रवृत्ति।",
    minAge: 15, 
    maxAge: 35, 
    gender: "Any", 
    maxIncome: 250000, 
    categories: ["SC", "ST", "OBC"], 
    occupation: ["Student"],
    details: "• **Eligibility:** Residents of Jharkhand with annual family income below ₹2.5 Lakh.\n• **Documents:** Aadhaar, Caste, Income, Residence, Bonafide Certificates.\n• **Website:** ekalyan.cgg.gov.in", 
    hindiDetails: "• **कौन आवेदन कर सकता है:** झारखंड के निवासी, और परिवार की आय ₹2.5 लाख से कम हो।\n• **दस्तावेज:** आधार, जाति, आय, आवासीय, बोनाफाइड।\n• **वेबसाइट:** ekalyan.cgg.gov.in",
    launchYear: "2013", 
    lastVerified: "March 15, 2026",
    lastDate: "January 31, 2026 (for session 2025-26)",
    detailedContent: [
      {
        title: "Simple Explanation",
        icon: "1️⃣",
        content: "e-Kalyan is an initiative by the Government of Jharkhand. Its primary objective is to significantly increase the participation of students from Scheduled Tribes (ST), Scheduled Castes (SC), and Backward Classes (BC) in post-matric education. The scheme aims to provide them with equal opportunities for education, encourage them to pursue higher studies, and ultimately reduce dropout rates among these groups."
      },
      {
        title: "Ways to Apply",
        icon: "2️⃣",
        content: "The e-Kalyan portal primarily facilitates online services.\n\nScholarship Applications: Students typically apply for various post-matric scholarships online through the e-Kalyan portal. Specific application windows and detailed instructions are usually available on the official website.\n\nGrievance Registration: Students can also register grievances related to e-Kalyan services through an online form. This service is fully online."
      },
      {
        title: "Step-by-Step Process",
        icon: "3️⃣",
        content: "For Grievance Registration:\n1. Visit the official Government Services Portal of India or the e-Kalyan portal.\n2. Locate the \"e-Kalyan Grievance Registration Form for Students, Jharkhand.\"\n3. Fill in the required details in the online form.\n4. Submit the form electronically.\n\nFor Scholarship Applications:\n1. Registration: Creating an account on the e-Kalyan portal.\n2. Application Form: Filling out the online application form with personal, academic, and income details.\n3. Document Upload: Uploading scanned copies of required documents.\n4. Submission: Final submission of the application.\n5. Tracking: Checking the application status online."
      },
      {
        title: "Documents Required",
        icon: "4️⃣",
        content: "Common documents typically include:\n• Aadhaar Card\n• Caste Certificate\n• Income Certificate\n• Residence Certificate\n• Previous Year's Mark Sheets\n• Bank Account Details\n• College/School Bonafide Certificate"
      },
      {
        title: "Who is Eligible",
        icon: "6️⃣",
        content: "Students belonging to the following categories are eligible for benefits under e-Kalyan, specifically for post-matric education:\n• Scheduled Tribes (ST)\n• Scheduled Castes (SC)\n• Backward Classes (BC)\n\nThese schemes are primarily for students from Jharkhand."
      },
      {
        title: "Official Apply Links",
        icon: "9️⃣",
        content: "• e-Kalyan Grievance Registration Form ↗\n• e-Kalyan Official Portal FAQs ↗\n• e-Kalyan Application Status ↗"
      }
    ],
    applyLinks: [
      { label: "e-Kalyan Grievance Form", url: "https://ekalyan.cgg.gov.in" },
      { label: "Check Application Status", url: "https://ekalyan.cgg.gov.in" }
    ],
    sources: ["e-Kalyan Official Portal", "Jharkhand Welfare Dept"]
  }, 
  { 
    id: 2, 
    name: "Mukhyamantri Maiyan Samman Yojana", 
    hindiName: "मुख्यमंत्री मंईयां सम्मान योजना",
    type: "State",
    categoryHeading: "👩 Women Empowerment", 
    hindiCategoryHeading: "👩 महिला सशक्तिकरण",
    desc: "Monthly financial assistance for the empowerment of women in Jharkhand.", 
    hindiDesc: "झारखंड की महिलाओं के लिए मासिक आर्थिक सहायता।",
    minAge: 18, 
    maxAge: 50, 
    gender: "Female", 
    maxIncome: 800000, 
    categories: ["General", "SC", "ST", "OBC"], 
    geography: "Rural",
    target_ration_card: ["Pink", "Yellow", "Green"],
    details: "• **Benefit:** ₹2500 per month directly into bank account.\n• **Documents:** Aadhaar, Bank Passbook, Ration Card.\n• **Portal:** mmmsy.jharkhand.gov.in or nearest Pragya Kendra.", 
    hindiDetails: "• **लाभ:** ₹2500 प्रति माह सीधे बैंक खाते में।\n• **दस्तावेज:** आधार, बैंक पासबुक, राशन कार्ड।\n• **कहाँ:** mmmsy.jharkhand.gov.in या प्रज्ञा केंद्र।",
    launchYear: "August 1, 2024", 
    lastVerified: "March 15, 2026",
    detailedContent: [
      {
        title: "Simple Explanation",
        icon: "1️⃣",
        content: "The Jharkhand Mukhyamantri Maiyan Samman Yojana (JMMSY) is a flagship welfare scheme aimed at providing financial independence to women. It provides a monthly 'honorarium' to eligible women to support their daily needs and improve their social standing."
      },
      {
        title: "Ways to Apply",
        icon: "2️⃣",
        content: "Online: Through the official portal mmmsy.jharkhand.gov.in via CSC/Pragya Kendras.\n\nOffline: By submitting physical forms at specialized camps (Panchayat level) or Anganwadi centers."
      },
      {
        title: "Step-by-Step Process",
        icon: "3️⃣",
        content: "1. Registration: Visit the nearest Pragya Kendra or Panchayat Camp.\n2. Documentation: Provide Aadhaar and Bank details.\n3. Verification: Field verification by local authorities.\n4. Approval: Once approved, the first installment is credited via DBT.\n5. Status: Check status on mmmsy.jharkhand.gov.in using Aadhaar number."
      },
      {
        title: "Documents Required",
        icon: "4️⃣",
        content: "• Aadhaar Card (Linked to mobile & bank)\n• Bank Passbook (Aadhaar Seeded)\n• Ration Card (Green/Yellow/Pink)\n• Passport size photograph\n• Self-Declaration Form"
      },
      {
        title: "Who is Eligible",
        icon: "6️⃣",
        content: "• Female resident of Jharkhand.\n• Age: 18 to 50 years.\n• Family must hold a valid Ration Card.\n• Not a regular government employee or taxpayer."
      },
      {
        title: "Official Apply Links",
        icon: "9️⃣",
        content: "• JMMSY Official Portal ↗\n• Check Application Status ↗"
      }
    ],
    applyLinks: [
      { label: "JMMSY Official Portal", url: "https://mmmsy.jharkhand.gov.in" },
      { label: "Check Status", url: "https://mmmsy.jharkhand.gov.in" }
    ],
    sources: ["WCD Department, Jharkhand", "Official MMMSY Portal"]
  }, 
  { 
    id: 3, 
    name: "Guruji Student Credit Card", 
    hindiName: "गुरुजी स्टूडेंट क्रेडिट कार्ड योजना",
    type: "State",
    categoryHeading: "🎓 Higher Education Loan", 
    hindiCategoryHeading: "🎓 उच्च शिक्षा ऋण",
    desc: "Low-interest education loans for students without any collateral.", 
    hindiDesc: "बिना किसी सुरक्षा (collateral) के पढ़ाई के लिए सस्ता ऋण।",
    minAge: 18, 
    maxAge: 40, 
    gender: "Any", 
    maxIncome: 9999999, 
    categories: ["General", "SC", "ST", "OBC"], 
    details: "• **Benefit:** Education loan up to ₹15 Lakh at only 4% simple interest.\n• **Documents:** Aadhaar, PAN Card, Admission Letter.\n• **Portal:** gscc.jharkhand.gov.in", 
    hindiDetails: "• **लाभ:** ₹15 लाख तक का ऋण केवल 4% ब्याज पर।\n• **दस्तावेज:** आधार, पैन, प्रवेश पत्र (Admission letter)।",
    launchYear: "January 21, 2025", 
    lastVerified: "March 15, 2026",
    detailedContent: [
      {
        title: "Simple Explanation",
        icon: "1️⃣",
        content: "The Guruji Student Credit Card (GSCC) scheme provides collateral-free education loans to students of Jharkhand. It aims to ensure that no student is deprived of higher education due to financial constraints."
      },
      {
        title: "Ways to Apply",
        icon: "2️⃣",
        content: "Students can apply online through the official GSCC portal or visit designated help desks in educational institutions."
      },
      {
        title: "Step-by-Step Process",
        icon: "3️⃣",
        content: "1. Online Registration on the GSCC portal.\n2. Filling out the application with academic and institution details.\n3. Uploading required documents (Admission letter, Fee structure).\n4. Bank verification and approval.\n5. Issuance of the Credit Card/Loan disbursement."
      },
      {
        title: "Documents Required",
        icon: "4️⃣",
        content: "• Aadhaar Card of Student & Co-borrower (Parent).\n• PAN Card.\n• 10th/12th Marksheets.\n• Admission Letter from a recognized institution.\n• Detailed Fee Structure.\n• Residence Certificate of Jharkhand."
      },
      {
        title: "Who is Eligible",
        icon: "6️⃣",
        content: "• Resident of Jharkhand.\n• Age up to 40 years.\n• Must have secured admission in a recognized higher education institution (General/Technical/Professional)."
      },
      {
        title: "Official Apply Links",
        icon: "9️⃣",
        content: "• Guruji Student Credit Card Portal ↗"
      }
    ],
    applyLinks: [
      { label: "GSCC Portal", url: "https://gscc.jharkhand.gov.in" }
    ],
    sources: ["Higher Education Dept, Jharkhand"]
  },
  {
    id: 4,
    name: "Abua Awas Yojana",
    hindiName: "अबूआ आवास योजना",
    type: "State",
    categoryHeading: "🏠 Housing Support",
    hindiCategoryHeading: "🏠 आवास सहायता (घर)",
    desc: "A state-funded housing scheme providing 3-room permanent houses to homeless families.",
    hindiDesc: "बेघर परिवारों को 3 कमरों वाला पक्का घर देने की योजना।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 300000,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    details: "• **Benefit:** ₹2 Lakh in 4 installments + 95 days MGNREGA wages.\n• **Documents:** Aadhaar, Ration Card, Job Card, Bank Passbook.\n• **Portal:** Nearest Block Office or Panchayat Camp.",
    hindiDetails: "• **लाभ:** ₹2 लाख (4 किस्तों में) + 95 दिनों की मनरेगा मजदूरी।\n• **दस्तावेज:** आधार, राशन कार्ड, जॉब कार्ड, बैंक पासबुक।",
    launchYear: "2023",
    lastVerified: "March 15, 2026",
    detailedContent: [
      {
        title: "Simple Explanation",
        icon: "1️⃣",
        content: "The Abua Awas Yojana is Jharkhand's own housing scheme for those who were left out of PMAY (Pradhan Mantri Awas Yojana). It provides a decent 3-room house with a kitchen."
      },
      {
        title: "Step-by-Step Process",
        icon: "3️⃣",
        content: "1. Apply during 'Aapki Yojana, Aapki Sarkar, Aapke Dwar' camps.\n2. Verification by Gram Sabha and Block officials.\n3. Geo-tagging of the old kucha house.\n4. Approval and release of the first installment."
      },
      {
        title: "Documents Required",
        icon: "4️⃣",
        content: "• Aadhaar Card\n• MGNREGA Job Card\n• Ration Card\n• Bank Passbook\n• Photograph of current house"
      }
    ],
    sources: ["Rural Development Dept, Jharkhand"]
  },
  {
    id: 5,
    name: "Savitribai Phule Kishori Samriddhi Yojana",
    hindiName: "सावित्रीबाई फुले किशोरी समृद्धि योजना",
    type: "State",
    categoryHeading: "👧 Girl Child Welfare",
    hindiCategoryHeading: "👧 बालिका कल्याण",
    desc: "Financial assistance to adolescent girls for education and to prevent child marriage.",
    hindiDesc: "किशोरियों की शिक्षा और बाल विवाह रोकने के लिए आर्थिक सहायता।",
    minAge: 13,
    maxAge: 19,
    gender: "Female",
    maxIncome: 500000,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Student"],
    details: "• **Benefit:** Up to ₹40,000 total assistance in grades 8 to 12 and at age 18.\n• **Documents:** School Certificate, Aadhaar, Mother's Aadhaar.\n• **Portal:** Apply via School or Anganwadi.",
    hindiDetails: "• **लाभ:** कक्षा 8 से 12 तक और 18 साल की उम्र पर कुल ₹40,000 तक की सहायता।\n• **दस्तावेज:** स्कूल सर्टिफिकेट, आधार, माता का आधार।",
    launchYear: "2022",
    lastVerified: "March 15, 2026",
    detailedContent: [
      {
        title: "Benefits Breakdown",
        icon: "💰",
        content: "Class 8 & 9: ₹2,500 each | Class 10, 11 & 12: ₹5,000 each | Age 18-19: ₹20,000 one-time grant."
      }
    ],
    sources: ["WCD Department, Jharkhand"]
  },
  {
    id: 6,
    name: "Mukhyamantri Gram Gaadi Yojana",
    hindiName: "मुख्यमंत्री ग्राम गाड़ी योजना",
    type: "State",
    categoryHeading: "🚌 Rural Transport",
    hindiCategoryHeading: "🚌 ग्रामीण परिवहन",
    desc: "Free or subsidized travel for students, seniors, and disabled citizens in rural areas.",
    hindiDesc: "ग्रामीण क्षेत्रों में छात्रों, बुजुर्गों और दिव्यांगों के लिए मुफ्त या रियायती यात्रा।",
    minAge: 5,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    details: "• **Benefit:** Free travel cards for eligible categories.\n• **Documents:** ID Card, Category Certificate.\n• **Portal:** District Transport Office.",
    hindiDetails: "• **लाभ:** पात्र श्रेणियों के लिए मुफ्त यात्रा पास।\n• **दस्तावेज:** पहचान पत्र, श्रेणी प्रमाण पत्र।",
    launchYear: "2024",
    lastVerified: "March 15, 2026",
    sources: ["Transport Dept, Jharkhand"]
  },
  {
    id: 7,
    name: "Birsa Harit Gram Yojana",
    hindiName: "बिरसा हरित ग्राम योजना",
    type: "State",
    categoryHeading: "🌳 Horticulture & Livelihood",
    hindiCategoryHeading: "🌳 बागवानी और आजीविका",
    desc: "Subsidy for fruit plantation on private land to provide sustainable income to rural families.",
    hindiDesc: "ग्रामीण परिवारों को स्थायी आय देने के लिए निजी भूमि पर फलदार वृक्षारोपण।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 200000,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    requires_land: true,
    details: "• **Benefit:** Saplings, fencing, and maintenance labor via MGNREGA.\n• **Documents:** Land Documents, MGNREGA Job Card.\n• **Portal:** BDO Office / Gram Panchayat.",
    hindiDetails: "• **लाभ:** फलदार पौधे, घेराबंदी और मनरेगा के तहत रखरखाव।\n• **दस्तावेज:** जमीन के कागज, जॉब कार्ड।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["Rural Development Dept, Jharkhand"]
  },
  {
    id: 8,
    name: "Mukhyamantri Pashudhan Vikas Yojana",
    hindiName: "मुख्यमंत्री पशुधन विकास योजना",
    type: "State",
    categoryHeading: "🐄 Animal Husbandry",
    hindiCategoryHeading: "🐄 पशुपालन विकास",
    desc: "Subsidy on dairy, poultry, and goat farming to boost rural economy.",
    hindiDesc: "ग्रामीण अर्थव्यवस्था को बढ़ावा देने के लिए डेयरी, मुर्गी पालन और बकरी पालन पर सब्सिडी।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 500000,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** 50% to 90% subsidy on purchase of livestock.\n• **Documents:** Aadhaar, Bank Passbook, Training Certificate (optional).\n• **Portal:** District Animal Husbandry Office.",
    hindiDetails: "• **लाभ:** पशुओं की खरीद पर 50% से 90% तक की सब्सिडी।\n• **दस्तावेज:** आधार, बैंक पासबुक, प्रशिक्षण प्रमाण पत्र।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Animal Husbandry Dept, Jharkhand"]
  },
  {
    id: 9,
    name: "Jharkhand State Food Security Scheme (Green Ration Card)",
    hindiName: "झारखंड राज्य खाद्य सुरक्षा योजना (हरा राशन कार्ड)",
    type: "State",
    categoryHeading: "🍎 Food Security",
    hindiCategoryHeading: "🍎 खाद्य सुरक्षा (राशन)",
    desc: "Subsidized food grains for families not covered under the National Food Security Act.",
    hindiDesc: "उन परिवारों के लिए रियायती अनाज जो राष्ट्रीय खाद्य सुरक्षा अधिनियम के तहत नहीं आते।",
    minAge: 1,
    maxAge: 99,
    gender: "Any",
    maxIncome: 100000,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** 5kg food grains per person at ₹1/kg.\n• **Documents:** Aadhaar, Self-declaration of income.\n• **Portal:** aahar.jharkhand.gov.in",
    hindiDetails: "• **लाभ:** ₹1/किलो की दर से प्रति व्यक्ति 5 किलो अनाज।\n• **दस्तावेज:** आधार, आय का स्व-घोषणा पत्र।",
    launchYear: "2020",
    lastVerified: "March 15, 2026",
    sources: ["Food & Public Distribution Dept, Jharkhand"]
  },
  {
    id: 10,
    name: "Marang Gomke Jaipal Singh Munda Transnational Scholarship",
    hindiName: "मरांग गोमके जयपाल सिंह मुंडा विदेशी छात्रवृत्ति",
    type: "State",
    categoryHeading: "🌍 Overseas Education",
    hindiCategoryHeading: "🌍 विदेश में उच्च शिक्षा",
    desc: "Full funding for higher studies (Masters/M.Phil) in UK and Ireland for talented students.",
    hindiDesc: "प्रतिभावान छात्रों के लिए यूके और आयरलैंड में उच्च शिक्षा (मास्टर्स) के लिए पूर्ण वित्त पोषण।",
    minAge: 18,
    maxAge: 35,
    gender: "Any",
    maxIncome: 1200000,
    categories: ["SC", "ST", "OBC", "Minority"],
    occupation: ["Student"],
    details: "• **Benefit:** Tuition fees, living expenses, and airfare covered.\n• **Documents:** Admission offer, Caste Certificate, Income Certificate.\n• **Portal:** mgjsmscholarship.jharkhand.gov.in",
    hindiDetails: "• **लाभ:** ट्यूशन फीस, रहने का खर्च और हवाई किराया।\n• **दस्तावेज:** प्रवेश प्रस्ताव पत्र, जाति प्रमाण पत्र, आय प्रमाण पत्र।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Welfare Dept, Jharkhand"]
  },
  {
    id: 11,
    name: "Mukhyamantri Sarvajan Pension Yojana",
    hindiName: "मुख्यमंत्री सर्वजन पेंशन योजना",
    type: "State",
    categoryHeading: "👴 Social Security",
    hindiCategoryHeading: "👴 सामाजिक सुरक्षा (पेंशन)",
    desc: "Universal pension scheme for seniors, widows, and disabled persons without complex criteria.",
    hindiDesc: "बुजुर्गों, विधवाओं और दिव्यांगों के लिए बिना किसी जटिल मानदंड के सार्वभौमिक पेंशन योजना।",
    minAge: 60,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    isPension: true,
    details: "• **Benefit:** ₹1,000 per month directly to bank account.\n• **Documents:** Aadhaar, Voter ID, Bank Details.\n• **Portal:** Block Office / Pragya Kendra.",
    hindiDetails: "• **लाभ:** ₹1,000 प्रति माह सीधे बैंक खाते में।\n• **दस्तावेज:** आधार, वोटर आईडी, बैंक विवरण।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["WCD Department, Jharkhand"]
  },
  {
    id: 12,
    name: "Jharkhand Mukhyamantri Sarthi Yojana",
    hindiName: "झारखंड मुख्यमंत्री सारथी योजना",
    type: "State",
    categoryHeading: "🛠️ Skill Development",
    hindiCategoryHeading: "🛠️ कौशल विकास (ट्रेनिंग)",
    desc: "Free skill training and placement assistance for unemployed youth.",
    hindiDesc: "बेरोजगार युवाओं के लिए मुफ्त कौशल प्रशिक्षण और प्लेसमेंट सहायता।",
    minAge: 18,
    maxAge: 35,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    occupation: ["Unemployed"],
    details: "• **Benefit:** Free training + ₹1,000-1,500 monthly allowance during training.\n• **Documents:** Aadhaar, Educational Certificates.\n• **Portal:** Jharkhand Skill Development Mission.",
    hindiDetails: "• **लाभ:** मुफ्त ट्रेनिंग + ट्रेनिंग के दौरान ₹1,000-1,500 मासिक भत्ता।\n• **दस्तावेज:** आधार, शैक्षणिक प्रमाण पत्र।",
    launchYear: "2023",
    lastVerified: "March 15, 2026",
    sources: ["Labour & Employment Dept, Jharkhand"]
  },
  {
    id: 13,
    name: "Mukhyamantri Rojgar Srijan Yojana",
    hindiName: "मुख्यमंत्री रोजगार सृजन योजना",
    type: "State",
    categoryHeading: "💼 Entrepreneurship Loan",
    hindiCategoryHeading: "💼 स्वरोजगार ऋण (बिजनेस)",
    desc: "Subsidized loans for youth to start their own business or purchase commercial vehicles.",
    hindiDesc: "युवाओं को अपना व्यवसाय शुरू करने या वाणिज्यिक वाहन खरीदने के लिए रियायती ऋण।",
    minAge: 18,
    maxAge: 45,
    gender: "Any",
    maxIncome: 500000,
    categories: ["SC", "ST", "OBC", "Minority", "Disabled"],
    details: "• **Benefit:** Loan up to ₹25 Lakh with 40% subsidy (max ₹5 Lakh).\n• **Documents:** Project Report, Caste Certificate, Aadhaar.\n• **Portal:** Jharkhand Tribal Development Society / District Offices.",
    hindiDetails: "• **लाभ:** 40% सब्सिडी के साथ ₹25 लाख तक का ऋण।\n• **दस्तावेज:** प्रोजेक्ट रिपोर्ट, जाति प्रमाण पत्र, आधार।",
    launchYear: "2021",
    lastVerified: "March 15, 2026",
    sources: ["Welfare Dept, Jharkhand"]
  },
  {
    id: 14,
    name: "Paddy Procurement Scheme (MSP)",
    hindiName: "धान अधिप्राप्ति योजना (एमएसपी)",
    type: "State",
    categoryHeading: "🌾 Agriculture Support",
    hindiCategoryHeading: "🌾 कृषि सहायता (धान)",
    desc: "Direct purchase of paddy from farmers at Minimum Support Price plus state bonus.",
    hindiDesc: "न्यूनतम समर्थन मूल्य (MSP) और राज्य बोनस पर किसानों से धान की सीधी खरीद।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    geography: "Rural",
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** Guaranteed price + Bonus paid directly via DBT.\n• **Documents:** Farmer Registration ID, Land Receipt.\n• **Portal:** Jharkhand Kharif Procurement Portal.",
    hindiDetails: "• **लाभ:** गारंटीकृत मूल्य + सीधा बैंक खाते में भुगतान।\n• **दस्तावेज:** किसान पंजीकरण आईडी, लगान रसीद।",
    launchYear: "Every Kharif Season",
    lastVerified: "March 15, 2026",
    sources: ["Food & Civil Supplies Dept, Jharkhand"]
  },
  {
    id: 15,
    name: "Mukhyamantri Kanyadan Yojana",
    hindiName: "मुख्यमंत्री कन्यादान योजना",
    type: "State",
    categoryHeading: "💍 Marriage Assistance",
    hindiCategoryHeading: "💍 विवाह सहायता",
    desc: "One-time financial assistance to BPL families for the marriage of their daughters.",
    hindiDesc: "बीपीएल परिवारों को उनकी बेटियों की शादी के लिए एकमुश्त वित्तीय सहायता।",
    minAge: 18,
    maxAge: 99,
    gender: "Female",
    maxIncome: 72000,
    categories: ["General", "SC", "ST", "OBC"],
    target_ration_card: ["Yellow", "Pink"],
    details: "• **Benefit:** ₹30,000 financial assistance.\n• **Documents:** BPL Card, Age Proof of Bride, Marriage Card.\n• **Portal:** Block Development Office.",
    hindiDetails: "• **लाभ:** ₹30,000 की वित्तीय सहायता।\n• **दस्तावेज:** बीपीएल कार्ड, दुल्हन का आयु प्रमाण, शादी का कार्ड।",
    launchYear: "2004",
    lastVerified: "March 15, 2026",
    sources: ["WCD Department, Jharkhand"]
  },
  {
    id: 16,
    name: "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
    hindiName: "प्रधानमंत्री मातृ वंदना योजना",
    type: "Central",
    categoryHeading: "🤰 Maternity Benefit",
    hindiCategoryHeading: "🤰 मातृत्व लाभ",
    desc: "Cash incentive for pregnant and lactating mothers for the first living child.",
    hindiDesc: "गर्भवती और स्तनपान कराने वाली माताओं के लिए नकद प्रोत्साहन राशि।",
    minAge: 19,
    maxAge: 45,
    gender: "Female",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    details: "• **Benefit:** ₹5,000 in three installments.\n• **Documents:** MCP Card, Aadhaar, Bank Passbook.\n• **Portal:** pmmvy-cas.nic.in or Anganwadi.",
    hindiDetails: "• **लाभ:** तीन किस्तों में ₹5,000।\n• **दस्तावेज:** एमसीपी कार्ड, आधार, बैंक पासबुक।",
    launchYear: "2017",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of WCD, GoI"]
  },
  {
    id: 17,
    name: "Ayushman Bharat - PMJAY",
    hindiName: "आयुष्मान भारत - पीएमजेएवाई",
    type: "Central",
    categoryHeading: "🏥 Health Insurance",
    hindiCategoryHeading: "🏥 स्वास्थ्य बीमा",
    desc: "World's largest health insurance scheme providing ₹5 Lakh cover per family per year.",
    hindiDesc: "दुनिया की सबसे बड़ी स्वास्थ्य बीमा योजना, प्रति परिवार ₹5 लाख का कवर।",
    minAge: 0,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    target_ration_card: ["Yellow", "Pink", "Green"],
    details: "• **Benefit:** Cashless treatment up to ₹5 Lakh in empanelled hospitals.\n• **Documents:** Ration Card, Aadhaar Card.\n• **Portal:** pmjay.gov.in or nearest Common Service Centre.",
    hindiDetails: "• **लाभ:** सूचीबद्ध अस्पतालों में ₹5 लाख तक का कैशलेस इलाज।\n• **दस्तावेज:** राशन कार्ड, आधार कार्ड।",
    launchYear: "2018",
    lastVerified: "March 15, 2026",
    sources: ["National Health Authority, GoI"]
  },
  {
    id: 18,
    name: "PM-Kisan Samman Nidhi",
    hindiName: "पीएम-किसान सम्मान निधि",
    type: "Central",
    categoryHeading: "👨‍🌾 Income Support for Farmers",
    hindiCategoryHeading: "👨‍🌾 किसानों के लिए आय सहायता",
    desc: "Annual financial support of ₹6,000 to all land-holding farmer families in India.",
    hindiDesc: "भारत के सभी भूमिधारक किसान परिवारों को ₹6,000 की वार्षिक वित्तीय सहायता।",
    minAge: 18,
    maxAge: 99,
    gender: "Any",
    maxIncome: 9999999,
    categories: ["General", "SC", "ST", "OBC"],
    requires_land: true,
    occupation: ["Farmer"],
    details: "• **Benefit:** ₹6,000 per year in three equal installments of ₹2,000.\n• **Documents:** Land Records, Aadhaar, Bank Account.\n• **Portal:** pmkisan.gov.in",
    hindiDetails: "• **लाभ:** ₹2,000 की तीन समान किस्तों में ₹6,000 प्रति वर्ष।\n• **दस्तावेज:** भूमि रिकॉर्ड, आधार, बैंक खाता।",
    launchYear: "2019",
    lastVerified: "March 15, 2026",
    sources: ["Ministry of Agriculture, GoI"]
  }
];

